# This file contains llgo's configuration for the buildbot-slave Juju charm.
# 
# The slave is deployed with the following command in a Juju environment:
#     juju deploy cs:~axwalk/buildbot-slave --config buildslave-config.yaml
#
# The charm generates a random password on first run, in the file
# /srv/buildbot/password. If the password is regenerated, it must
# be updated in the buildbot master.
#
buildbot-slave:
  name: llgo-builder
  master: lab.llvm.org:9990
  admin-info: Andrew Wilkins <axwalk@gmail.com>
  apt-packages: subversion git cmake gcc g++ gccgo python-dev
  pip-versions: sqlalchemy==0.7.9 buildbot==0.8.5 buildbot_slave==0.8.5 twisted==12.0.0
  post-install: |
      #!/bin/bash
      #
      # Fetch, build and install Ninja.
      rm -fr /tmp/ninja
      cd /tmp && git clone git://github.com/martine/ninja.git
      cd /tmp/ninja && ./configure.py --bootstrap
      cp /tmp/ninja/ninja /usr/local/bin
      # Fetch and unpack Go.
      cd /tmp && wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
      sha1sum <<EOF
      5020af94b52b65cc9b6f11d50a67e4bae07b0aff go1.4.2.linux-amd64.tar.gz
      EOF
      cd /usr/local && tar xzf /tmp/go1.4.2.linux-amd64.tar.gz
      ln -f -s /usr/local/go/bin/go /usr/local/bin/go

