// Copyright 2026 Futz12 <pchar.cn>
// SPDX-License-Identifier: BSD-3-Clause

#version 450

#extension GL_GOOGLE_include_directive : enable
#include "vulkan_activation.comp"

layout(constant_id = 0) const int bias_term = 0;
layout(constant_id = 1) const int activation_type = 0;
layout(constant_id = 2) const float activation_param_0 = 0;
layout(constant_id = 3) const float activation_param_1 = 0;
layout(constant_id = 4) const int c = 0;

#define shape_constant_id_offset 5
layout(constant_id = shape_constant_id_offset + 0) const int cstep = 0;
layout(constant_id = shape_constant_id_offset + 1) const int block_x = 0;
layout(constant_id = shape_constant_id_offset + 2) const int outw = 0;
layout(constant_id = shape_constant_id_offset + 3) const int outcstep = 0;

layout(binding = 0) readonly buffer top_tm_blob { sfpvec4 top_tm_blob_data[]; };
layout(binding = 1) writeonly buffer top_blob { sfpvec4 top_blob_data[]; };
layout(binding = 2) readonly buffer bias_blob { sfpvec4 bias_data[]; };

layout(push_constant) uniform parameter
{
    int cstep;
    int block_x;
    int outw;
    int outcstep;
} p;

void main()
{
    int gx = int(gl_GlobalInvocationID.x);
    int gz = int(gl_GlobalInvocationID.z);

    if (gx >= psc(block_x) || gz >= c)
        return;

    // load 6 accumulated values from transform domain
    int v_tm_offset = gz * psc(cstep) + gx;

    afpvec4 m0 = buffer_ld4(top_tm_blob_data, v_tm_offset + 0 * psc(cstep) * c);
    afpvec4 m1 = buffer_ld4(top_tm_blob_data, v_tm_offset + 1 * psc(cstep) * c);
    afpvec4 m2 = buffer_ld4(top_tm_blob_data, v_tm_offset + 2 * psc(cstep) * c);
    afpvec4 m3 = buffer_ld4(top_tm_blob_data, v_tm_offset + 3 * psc(cstep) * c);
    afpvec4 m4 = buffer_ld4(top_tm_blob_data, v_tm_offset + 4 * psc(cstep) * c);
    afpvec4 m5 = buffer_ld4(top_tm_blob_data, v_tm_offset + 5 * psc(cstep) * c);

#define sq2    1.41421356237
#define sq2_m2 1.41421356237 * 2
#define sq2_d2 1.41421356237 / 2
#define sq2_d4 1.41421356237 / 4

    // const float otm[4][6] = {
    //     {1.0f, 1.0f,   1.0f,  1.0f,  1.0f,   0.0f},
    //     {0.0f, sq2/2, -sq2/2, sq2,   -sq2,   0.0f},
    //     {0.0f, 0.5f,   0.5f,  2.0f,  2.0f,   0.0f},
    //     {0.0f, sq2/4, -sq2/4, sq2*2, -sq2*2, 1.0f}
    // };

    // A^T transform (4x6) - only once (1D)
    afpvec4 y0 = m0 + m1 + m2 + m3 + m4;
    afpvec4 y1 = (m1 - m2) * afp(sq2_d2) + (m3 - m4) * afp(sq2);
    afpvec4 y2 = (m1 + m2) * afp(0.5) + (m3 + m4) * afp(2);
    afpvec4 y3 = m5 + (m1 - m2) * afp(sq2_d4) + (m3 - m4) * afp(sq2_m2);

    // bias
    if (bias_term == 1)
    {
        const afpvec4 bias_value = buffer_ld4(bias_data, gz);

        y0 = bias_value + y0;
        y1 = bias_value + y1;
        y2 = bias_value + y2;
        y3 = bias_value + y3;
    }

    // activation
    y0 = activation_afpvec4(y0, activation_type, activation_param_0, activation_param_1);
    y1 = activation_afpvec4(y1, activation_type, activation_param_0, activation_param_1);
    y2 = activation_afpvec4(y2, activation_type, activation_param_0, activation_param_1);
    y3 = activation_afpvec4(y3, activation_type, activation_param_0, activation_param_1);

    // store 4 output elements
    int x = gx * 4;
    int v_offset = gz * psc(outcstep) + x;

    buffer_st4(top_blob_data, v_offset + 0, y0);
    if (x + 1 < psc(outw)) buffer_st4(top_blob_data, v_offset + 1, y1);
    if (x + 2 < psc(outw)) buffer_st4(top_blob_data, v_offset + 2, y2);
    if (x + 3 < psc(outw)) buffer_st4(top_blob_data, v_offset + 3, y3);
}
