// Copyright 2026 Futz12 <pchar.cn>
// SPDX-License-Identifier: BSD-3-Clause

#version 450

#extension GL_GOOGLE_include_directive : enable
#include "vulkan_activation.comp"

layout(constant_id = 0) const int kernel_w = 1;
layout(constant_id = 1) const int dilation_w = 1;
layout(constant_id = 2) const int stride_w = 1;
layout(constant_id = 3) const int bias_term = 0;
layout(constant_id = 4) const int group = 1;
layout(constant_id = 5) const int activation_type = 0;
layout(constant_id = 6) const float activation_param_0 = 0;
layout(constant_id = 7) const float activation_param_1 = 0;

#define shape_constant_id_offset 8
layout(constant_id = shape_constant_id_offset + 0) const int dims = 0;
layout(constant_id = shape_constant_id_offset + 1) const int w = 0;
layout(constant_id = shape_constant_id_offset + 2) const int h = 0;
layout(constant_id = shape_constant_id_offset + 3) const int c = 0;
layout(constant_id = shape_constant_id_offset + 4) const int cstep = 0;

layout(constant_id = shape_constant_id_offset + 5) const int outdims = 0;
layout(constant_id = shape_constant_id_offset + 6) const int outw = 0;
layout(constant_id = shape_constant_id_offset + 7) const int outh = 0;
layout(constant_id = shape_constant_id_offset + 8) const int outc = 0;
layout(constant_id = shape_constant_id_offset + 9) const int outcstep = 0;

layout(binding = 0) readonly buffer bottom_blob { sfp bottom_blob_data[]; };
layout(binding = 1) writeonly buffer top_blob { sfp top_blob_data[]; };
layout(binding = 2) readonly buffer weight_blob { sfp weight_data[]; };
layout(binding = 3) readonly buffer bias_blob { sfp bias_data[]; };

layout(push_constant) uniform parameter
{
    int dims;
    int w;
    int h;
    int c;
    int cstep;

    int outdims;
    int outw;
    int outh;
    int outc;
    int outcstep;
} p;

void main()
{
    int gx = int(gl_GlobalInvocationID.x);
    int gy = int(gl_GlobalInvocationID.y);

    if (gx >= psc(outw) || gy >= psc(outh))
        return;

    afp sum;

    if (bias_term == 1)
    {
        sum = buffer_ld1(bias_data, gy);
    }
    else
    {
        sum = afp(0.f);
    }

    // depth-wise convolution
    int w_offset = gy * kernel_w;
    int v_offset = gy * psc(w) + gx * stride_w;

    for (int x = 0; x < kernel_w; x++)
    {
        sum += buffer_ld1(weight_data, w_offset + x) * buffer_ld1(bottom_blob_data, v_offset + x * dilation_w);
    }

    sum = activation_afp(sum, activation_type, activation_param_0, activation_param_1);

    const int gi = gy * psc(outw) + gx;

    buffer_st1(top_blob_data, gi, sum);
}
