// Copyright 2026 Futz12 <pchar.cn>
// SPDX-License-Identifier: BSD-3-Clause

#version 450

#extension GL_GOOGLE_include_directive : enable
#include "vulkan_activation.comp"

layout(constant_id = 0) const int bias_term = 0;
layout(constant_id = 1) const int activation_type = 0;
layout(constant_id = 2) const float activation_param_0 = 0;
layout(constant_id = 3) const float activation_param_1 = 0;
layout(constant_id = 4) const int c = 0;

#define shape_constant_id_offset 5
layout(constant_id = shape_constant_id_offset + 0) const int cstep = 0;

layout(constant_id = shape_constant_id_offset + 1) const int block_x = 0;
layout(constant_id = shape_constant_id_offset + 2) const int block_y = 0;
layout(constant_id = shape_constant_id_offset + 3) const int block_z = 0;

layout(constant_id = shape_constant_id_offset + 4) const int outw = 0;
layout(constant_id = shape_constant_id_offset + 5) const int outh = 0;
layout(constant_id = shape_constant_id_offset + 6) const int outd = 0;
layout(constant_id = shape_constant_id_offset + 7) const int outcstep = 0;

layout(binding = 0) readonly buffer top_tm_blob { sfpvec4 top_tm_blob_data[]; };
layout(binding = 1) writeonly buffer top_blob { sfpvec4 top_blob_data[]; };
layout(binding = 2) readonly buffer bias_blob { sfpvec4 bias_data[]; };

layout(push_constant) uniform parameter
{
    int cstep;

    int block_x;
    int block_y;
    int block_z;

    int outw;
    int outh;
    int outd;
    int outcstep;
} p;

void main()
{
    int gx = int(gl_GlobalInvocationID.x);
    int gy = int(gl_GlobalInvocationID.y);
    int gz = int(gl_GlobalInvocationID.z);

    if (gx >= psc(block_x) || gy >= psc(block_y) * psc(block_z) || gz >= c)
        return;

    const int by = gy % psc(block_y);
    const int bz = gy / psc(block_y);

    // load 64, coef = (i*4+j)*4+k
    int v_tm_offset = gz * psc(cstep) + gy * psc(block_x) + gx;

    afpvec4 v[4][4][4];
    for (int i = 0; i < 4; i++)
    {
        for (int j = 0; j < 4; j++)
        {
            for (int k = 0; k < 4; k++)
            {
                v[i][j][k] = buffer_ld4(top_tm_blob_data, v_tm_offset + ((i * 4 + j) * 4 + k) * psc(cstep) * c);
            }
        }
    }

    // A^T along z (k)
    afpvec4 m1[4][4][2];
    for (int i = 0; i < 4; i++)
    {
        for (int j = 0; j < 4; j++)
        {
            m1[i][j][0] = v[i][j][0] + v[i][j][1] + v[i][j][2];
            m1[i][j][1] = v[i][j][1] - v[i][j][2] + v[i][j][3];
        }
    }

    // A^T along y (j)
    afpvec4 m2[4][2][2];
    for (int i = 0; i < 4; i++)
    {
        for (int k = 0; k < 2; k++)
        {
            m2[i][0][k] = m1[i][0][k] + m1[i][1][k] + m1[i][2][k];
            m2[i][1][k] = m1[i][1][k] - m1[i][2][k] + m1[i][3][k];
        }
    }

    // A^T along x (i)
    afpvec4 outv[2][2][2];
    for (int j = 0; j < 2; j++)
    {
        for (int k = 0; k < 2; k++)
        {
            outv[0][j][k] = m2[0][j][k] + m2[1][j][k] + m2[2][j][k];
            outv[1][j][k] = m2[1][j][k] - m2[2][j][k] + m2[3][j][k];
        }
    }

    if (bias_term == 1)
    {
        const afpvec4 bias_value = buffer_ld4(bias_data, gz);
        outv[0][0][0] += bias_value;
        outv[0][0][1] += bias_value;
        outv[0][1][0] += bias_value;
        outv[0][1][1] += bias_value;
        outv[1][0][0] += bias_value;
        outv[1][0][1] += bias_value;
        outv[1][1][0] += bias_value;
        outv[1][1][1] += bias_value;
    }

    outv[0][0][0] = activation_afpvec4(outv[0][0][0], activation_type, activation_param_0, activation_param_1);
    outv[0][0][1] = activation_afpvec4(outv[0][0][1], activation_type, activation_param_0, activation_param_1);
    outv[0][1][0] = activation_afpvec4(outv[0][1][0], activation_type, activation_param_0, activation_param_1);
    outv[0][1][1] = activation_afpvec4(outv[0][1][1], activation_type, activation_param_0, activation_param_1);
    outv[1][0][0] = activation_afpvec4(outv[1][0][0], activation_type, activation_param_0, activation_param_1);
    outv[1][0][1] = activation_afpvec4(outv[1][0][1], activation_type, activation_param_0, activation_param_1);
    outv[1][1][0] = activation_afpvec4(outv[1][1][0], activation_type, activation_param_0, activation_param_1);
    outv[1][1][1] = activation_afpvec4(outv[1][1][1], activation_type, activation_param_0, activation_param_1);

    // store 2x2x2
    int x = gx * 2;
    int y = by * 2;
    int z = bz * 2;

    const int outbase = gz * psc(outcstep) + z * (psc(outh) * psc(outw)) + y * psc(outw) + x;

    buffer_st4(top_blob_data, outbase, outv[0][0][0]);
    if (x + 1 < psc(outw)) buffer_st4(top_blob_data, outbase + 1, outv[1][0][0]);
    if (y + 1 < psc(outh)) buffer_st4(top_blob_data, outbase + psc(outw), outv[0][1][0]);
    if (y + 1 < psc(outh) && x + 1 < psc(outw)) buffer_st4(top_blob_data, outbase + psc(outw) + 1, outv[1][1][0]);
    if (z + 1 < psc(outd))
    {
        const int outbase1 = outbase + psc(outh) * psc(outw);
        buffer_st4(top_blob_data, outbase1, outv[0][0][1]);
        if (x + 1 < psc(outw)) buffer_st4(top_blob_data, outbase1 + 1, outv[1][0][1]);
        if (y + 1 < psc(outh)) buffer_st4(top_blob_data, outbase1 + psc(outw), outv[0][1][1]);
        if (y + 1 < psc(outh) && x + 1 < psc(outw)) buffer_st4(top_blob_data, outbase1 + psc(outw) + 1, outv[1][1][1]);
    }
}
