// Copyright 2026 Futz12 <pchar.cn>
// SPDX-License-Identifier: BSD-3-Clause

#version 450

layout(constant_id = 0) const int c = 0;

#define shape_constant_id_offset 1
layout(constant_id = shape_constant_id_offset + 0) const int w = 0;
layout(constant_id = shape_constant_id_offset + 1) const int cstep = 0;
layout(constant_id = shape_constant_id_offset + 2) const int outcstep = 0;
layout(constant_id = shape_constant_id_offset + 3) const int block_x = 0;

layout(binding = 0) readonly buffer bottom_blob { sfpvec4 bottom_blob_data[]; };
layout(binding = 1) writeonly buffer bottom_tm_blob { sfpvec4 bottom_tm_blob_data[]; };

layout(push_constant) uniform parameter
{
    int w;
    int cstep;
    int outcstep;
    int block_x;
} p;

void main()
{
    int gx = int(gl_GlobalInvocationID.x);
    int gz = int(gl_GlobalInvocationID.z);

    if (gx >= psc(block_x) || gz >= c)
        return;

    // load 6 elements (1D: only x dimension)
    int sx = gx * 4;  // each tile produces 4 output elements

    int v_offset = gz * psc(cstep) + sx;

    afpvec4 d0 = buffer_ld4(bottom_blob_data, v_offset + 0);
    afpvec4 d1 = sx + 1 < psc(w) ? buffer_ld4(bottom_blob_data, v_offset + 1) : afpvec4(0.f);
    afpvec4 d2 = sx + 2 < psc(w) ? buffer_ld4(bottom_blob_data, v_offset + 2) : afpvec4(0.f);
    afpvec4 d3 = sx + 3 < psc(w) ? buffer_ld4(bottom_blob_data, v_offset + 3) : afpvec4(0.f);
    afpvec4 d4 = sx + 4 < psc(w) ? buffer_ld4(bottom_blob_data, v_offset + 4) : afpvec4(0.f);
    afpvec4 d5 = sx + 5 < psc(w) ? buffer_ld4(bottom_blob_data, v_offset + 5) : afpvec4(0.f);

#define sq2    1.41421356237
#define sq2_d2 1.41421356237 / 2

    // const float itm[6][6] = {
    //     {1.0f,  0.0f,  -2.5f,  0.0f,  1.0f, 0.0f},
    //     {0.0f, -sq2,   -2.0f,  sq2/2, 1.0f, 0.0f},
    //     {0.0f,  sq2,   -2.0f, -sq2/2, 1.0f, 0.0f},
    //     {0.0f, -sq2/2, -0.5f,  sq2,   1.0f, 0.0f},
    //     {0.0f,  sq2/2, -0.5f, -sq2,   1.0f, 0.0f},
    //     {0.0f,  1.0f,   0.0f,  -2.5f, 0.0f, 1.0f}
    // };

    // B^T transform (6x6) - only once (1D)
    afpvec4 v0 = d0 - d2 * afp(2.5) + d4;
    afpvec4 v1 = d4 - d2 * afp(2) + d3 * afp(sq2_d2) - d1 * afp(sq2);
    afpvec4 v2 = d4 - d2 * afp(2) - d3 * afp(sq2_d2) + d1 * afp(sq2);
    afpvec4 v3 = d4 - d2 * afp(0.5) + d3 * afp(sq2) - d1 * afp(sq2_d2);
    afpvec4 v4 = d4 - d2 * afp(0.5) - d3 * afp(sq2) + d1 * afp(sq2_d2);
    afpvec4 v5 = d1 - d3 * afp(2.5) + d5;

    // store 6 transformed values
    int v_tm_offset = gz * psc(outcstep) + gx;

    buffer_st4(bottom_tm_blob_data, v_tm_offset + 0 * psc(outcstep) * c, v0);
    buffer_st4(bottom_tm_blob_data, v_tm_offset + 1 * psc(outcstep) * c, v1);
    buffer_st4(bottom_tm_blob_data, v_tm_offset + 2 * psc(outcstep) * c, v2);
    buffer_st4(bottom_tm_blob_data, v_tm_offset + 3 * psc(outcstep) * c, v3);
    buffer_st4(bottom_tm_blob_data, v_tm_offset + 4 * psc(outcstep) * c, v4);
    buffer_st4(bottom_tm_blob_data, v_tm_offset + 5 * psc(outcstep) * c, v5);
}
