// Copyright 2025 Tencent
// SPDX-License-Identifier: BSD-3-Clause

#version 450

#extension GL_EXT_control_flow_attributes : require

#extension GL_KHR_shader_subgroup_basic : require

#extension GL_KHR_memory_scope_semantics : require
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#if ncnn_VK_KHR_cooperative_matrix
#extension GL_KHR_cooperative_matrix : require
#elif ncnn_VK_NV_cooperative_matrix
#extension GL_NV_cooperative_matrix : require
#endif

layout(constant_id = 0) const float alpha = 1.f;
layout(constant_id = 1) const float beta = 1.f;
layout(constant_id = 2) const int transA = 0;
layout(constant_id = 3) const int transB = 0;
layout(constant_id = 4) const int constantA = 0;
layout(constant_id = 5) const int constantB = 0;
layout(constant_id = 6) const int constantC = 0;
layout(constant_id = 7) const int GM = 0;
layout(constant_id = 8) const int GN = 0;
layout(constant_id = 9) const int GK = 0;
layout(constant_id = 10) const int constant_broadcast_type_C = 0;
layout(constant_id = 11) const int output_N1M = 0;
layout(constant_id = 12) const int output_elempack = 0;
layout(constant_id = 13) const int output_elemtype = 0;
layout(constant_id = 14) const int output_transpose = 0;
layout(constant_id = 15) const int A_elempack = 0;
layout(constant_id = 16) const int B_elempack = 0;
layout(constant_id = 17) const int out_elempack = 0;

layout(constant_id = 18 + 0) const uint M = 1;
layout(constant_id = 18 + 1) const uint N = 1;
layout(constant_id = 18 + 2) const uint K = 1;
layout(constant_id = 18 + 3) const uint subgroup_size = 32;
layout(constant_id = 18 + 4) const uint UNROLL_SG_M = 2;
layout(constant_id = 18 + 5) const uint UNROLL_SG_N = 2;
layout(constant_id = 18 + 6) const uint UNROLL_SG_K = 2;
layout(constant_id = 18 + 7) const uint UNROLL_WG_M = 2;
layout(constant_id = 18 + 8) const uint UNROLL_WG_N = 2;

// TODO psc more

layout(binding = 0) writeonly buffer top_blob { sfp top_blob_data[]; };
layout(binding = 1) readonly buffer A_blob { uvec2 A_blob_data[]; };
layout(binding = 2) readonly buffer B_blob { uvec2 B_blob_data[]; };
layout(binding = 3) readonly buffer C_blob { sfp C_blob_data[]; };
layout(binding = 4) writeonly buffer top_blob_4 { uvec2 top_blob_data_4[]; };

layout(push_constant) uniform parameter
{
    int GM;
    int GN;
    int GK;
    int broadcast_type_C;
    int A_dims;
    int A_hstep;
    int B_dims;
    int B_hstep;
    int outdims;
    int outhstep;
    int A_elempack;
    int B_elempack;
    int out_elempack;
} p;

const uint Md4 = M / 4;
const uint Nd4 = N / 4;
const uint Kd4 = K / 4;

// avoid bank conflict
#define PAD 1

const uint Md4p = Md4 + PAD;
const uint Nd4p = Nd4 + PAD;
const uint Kd4p = Kd4 + PAD;

const uint tmp_a_size = UNROLL_WG_M * UNROLL_SG_K * UNROLL_SG_M * (M * Kd4p > K * Md4p ? M * Kd4p : K * Md4p);
const uint tmp_b_size = UNROLL_WG_N * UNROLL_SG_K * UNROLL_SG_N * (K * Nd4p > N * Kd4p ? K * Nd4p : N * Kd4p);
const uint tmp_o_size = UNROLL_WG_N * UNROLL_WG_M * UNROLL_SG_N * UNROLL_SG_M * (M * Nd4p > N * Md4p ? M * Nd4p : N * Md4p);

// cannot alias output with a and b
// cm store may happen while another subgroup is loading
shared uvec2 tmp_a[tmp_a_size];
shared uvec2 tmp_b[tmp_b_size];
shared uvec2 tmp_o[tmp_o_size];

void main()
{
    // neither gl_SubgroupSize nor gl_WorkGroupSize.x is a constant
    const uint local_size = subgroup_size * UNROLL_WG_M * UNROLL_WG_N;

    // [ WG_UN * WG_UM * [ SG_UN * SG_UM * subgroup ] ]

    //                     <----WG_UN---->
    //       +---N--+-SG_UN+------+------+
    //       |      |      |      |XXXXXX|
    //       M             |       XXXX<----coopmat<M,N>
    //       |      |      |      |XXXXXX|
    //       +-- --SG0-- --+-- --SG2-- --+
    //       |      |      |      |      |
    //      SG_UM          |             |
    //       |      |      |      |      |
    //    ^  +------+--WORKGROUP--+------+
    //    |  |      |      |      |      |
    //    |  |             |             |
    //    |  |      |      |      |      |
    //  WG_UM+-- --SG1-- --+-- --SG3-- --+
    //    |  |      |      |      |      |
    //    |  |             |             |
    //    |  |      |      |      |      |
    //    v  +------+------+------+------+
    //

    const uint wgi = gl_WorkGroupID.x;
    const uint sgi = gl_SubgroupID;

    const uint wgmm = (psc(GM) + M * UNROLL_SG_M * UNROLL_WG_M - 1) / (M * UNROLL_SG_M * UNROLL_WG_M);
    const uint wgnn = (psc(GN) + N * UNROLL_SG_N * UNROLL_WG_N - 1) / (N * UNROLL_SG_N * UNROLL_WG_N);

    const uint wgmi = wgi / wgnn;
    const uint wgni = wgi % wgnn;

    const uint sgmi = sgi / UNROLL_WG_N;
    const uint sgni = sgi % UNROLL_WG_N;

    //     const uint mm = (psc(GM) + M - 1) / M;
    //     const uint nn = (psc(GN) + N - 1) / N;
    const uint kk = (psc(GK) + K - 1) / K;

    if (wgmi >= wgmm)
        return;

    const uint li = gl_LocalInvocationID.x;
    const uint si = gl_SubgroupInvocationID;

    const uint ni = (wgni * UNROLL_WG_N + sgni) * UNROLL_SG_N;
    const uint mi = (wgmi * UNROLL_WG_M + sgmi) * UNROLL_SG_M;

#if ncnn_VK_KHR_cooperative_matrix
    coopmat<afp, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> sum[UNROLL_SG_N][UNROLL_SG_M];
#elif ncnn_VK_NV_cooperative_matrix
#if NCNN_fp16_arithmetic
    fcoopmatNV<16, gl_ScopeSubgroup, M, N> sum[UNROLL_SG_N][UNROLL_SG_M];
#else
    fcoopmatNV<32, gl_ScopeSubgroup, M, N> sum[UNROLL_SG_N][UNROLL_SG_M];
#endif
#endif

    {
        [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
        {
            [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
            {
#if ncnn_VK_KHR_cooperative_matrix
                sum[zn][zm] = coopmat<afp, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(0.f);
#elif ncnn_VK_NV_cooperative_matrix
#if NCNN_fp16_arithmetic
                sum[zn][zm] = fcoopmatNV<16, gl_ScopeSubgroup, M, N>(0.f);
#else
                sum[zn][zm] = fcoopmatNV<32, gl_ScopeSubgroup, M, N>(0.f);
#endif
#endif
            }
        }
    }

    const int broadcast_type_C = constantC == 1 ? constant_broadcast_type_C : p.broadcast_type_C;

    if (broadcast_type_C == 0)
    {
        afp bias_value = buffer_ld1(C_blob_data, 0);

        [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
        {
            [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
            {
#if ncnn_VK_KHR_cooperative_matrix
                sum[zn][zm] = coopmat<afp, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(bias_value);
#elif ncnn_VK_NV_cooperative_matrix
#if NCNN_fp16_arithmetic
                sum[zn][zm] = fcoopmatNV<16, gl_ScopeSubgroup, M, N>(bias_value);
#else
                sum[zn][zm] = fcoopmatNV<32, gl_ScopeSubgroup, M, N>(bias_value);
#endif
#endif
            }
        }
    }
    if (broadcast_type_C == 1 || broadcast_type_C == 2)
    {
        [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
        {
#if ncnn_VK_KHR_cooperative_matrix
#if NCNN_bf16_storage || NCNN_bf16_packed
            coopmat<bfloat16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> bias;
#else
            coopmat<float16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> bias;
#endif
#if NCNN_bf16_storage || NCNN_fp16_storage
            coopMatLoad(bias, C_blob_data, ((wgmi * UNROLL_WG_M + sgmi) * UNROLL_SG_M + zm) * M, 0, gl_CooperativeMatrixLayoutColumnMajor);
#else
            // fp16p sfp is uint, fix offset
            coopMatLoad(bias, C_blob_data, ((wgmi * UNROLL_WG_M + sgmi) * UNROLL_SG_M + zm) * M / 2, 0, gl_CooperativeMatrixLayoutColumnMajor);
#endif
#elif ncnn_VK_NV_cooperative_matrix
            fcoopmatNV<16, gl_ScopeSubgroup, M, N> bias;
#if NCNN_fp16_storage
            coopMatLoadNV(bias, C_blob_data, ((wgmi * UNROLL_WG_M + sgmi) * UNROLL_SG_M + zm) * M, 0, true);
#else
            // fp16p sfp is uint, fix offset
            coopMatLoadNV(bias, C_blob_data, ((wgmi * UNROLL_WG_M + sgmi) * UNROLL_SG_M + zm) * M / 2, 0, true);
#endif
#endif

            [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
            {
#if NCNN_fp16_arithmetic
                sum[zn][zm] = bias;
#else
#if ncnn_VK_KHR_cooperative_matrix
                sum[zn][zm] = coopmat<float, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(bias);
#elif ncnn_VK_NV_cooperative_matrix
                sum[zn][zm] = fcoopmatNV<32, gl_ScopeSubgroup, M, N>(bias);
#endif
#endif
            }
        }
    }
    if (broadcast_type_C == 3)
    {
        const uint Nd4_M_USGM_USGN = Nd4 * M * UNROLL_SG_M * UNROLL_SG_N;
        const uint Nd4_M_USGM_USGN_d_subgroupsize = (Nd4_M_USGM_USGN + subgroup_size - 1) / subgroup_size;
        [[unroll]] for (uint q = 0; q < Nd4_M_USGM_USGN_d_subgroupsize; q++)
        {
            const uint siq = si + q * subgroup_size;

            if (Nd4_M_USGM_USGN % subgroup_size == 0 || siq < Nd4_M_USGM_USGN)
            {
                const uint zn = siq / (Nd4 * M * UNROLL_SG_M);
                const uint zmij = siq % (Nd4 * M * UNROLL_SG_M);
                const uint zm = zmij / (Nd4 * M);
                const uint ij = zmij % (Nd4 * M);
                const uint i = ij / Nd4;
                const uint j = ij % Nd4;

                const uint gm = (mi + zm) * M + i;
                const uint gn = (ni + zn) * Nd4 + j;

                if (gm < psc(GM))
                {
                    const uvec4 ci4 = gm * psc(GN) + gn * 4 + uvec4(0, 1, 2, 3);

                    vec2 va;
                    vec2 vb;
                    if (gn * 4 < psc(GN)) va.r = float(buffer_ld1(C_blob_data, ci4.r));
                    if (gn * 4 + 1 < psc(GN)) va.g = float(buffer_ld1(C_blob_data, ci4.g));
                    if (gn * 4 + 2 < psc(GN)) vb.r = float(buffer_ld1(C_blob_data, ci4.b));
                    if (gn * 4 + 3 < psc(GN)) vb.g = float(buffer_ld1(C_blob_data, ci4.a));

#if NCNN_bf16_storage || NCNN_bf16_packed
                    uvec2 v = uvec2(packBFloat2x16(va), packBFloat2x16(vb));
#else
                    uvec2 v = uvec2(packHalf2x16(va), packHalf2x16(vb));
#endif

                    tmp_o[(((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * M + i) * Nd4p + j] = v;
                }
            }
        }

        barrier();

        [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
        {
            [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
            {
#if ncnn_VK_KHR_cooperative_matrix
#if NCNN_fp16_arithmetic
                coopMatLoad(sum[zn][zm], tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Nd4p * M), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#else
#if NCNN_bf16_storage || NCNN_bf16_packed
                coopmat<bfloat16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> sum_fp16;
#else
                coopmat<float16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> sum_fp16;
#endif
                coopMatLoad(sum_fp16, tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Nd4p * M), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
                sum[zn][zm] = coopmat<float, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(sum_fp16);
#endif
#elif ncnn_VK_NV_cooperative_matrix
#if NCNN_fp16_arithmetic
                coopMatLoadNV(sum[zn][zm], tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Nd4p * M), Nd4p, false);
#else
                fcoopmatNV<16, gl_ScopeSubgroup, M, N> sum_fp16;
                coopMatLoadNV(sum_fp16, tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Nd4p * M), Nd4p, false);
                sum[zn][zm] = fcoopmatNV<32, gl_ScopeSubgroup, M, N>(sum_fp16);
#endif
#endif
            }
        }
    }
    if (broadcast_type_C == 4)
    {
        [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
        {
#if ncnn_VK_KHR_cooperative_matrix
#if NCNN_bf16_storage || NCNN_bf16_packed
            coopmat<bfloat16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> bias;
#else
            coopmat<float16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> bias;
#endif
#if NCNN_bf16_storage || NCNN_fp16_storage
            coopMatLoad(bias, C_blob_data, ((wgni * UNROLL_WG_N + sgni) * UNROLL_SG_N + zn) * N, 0, gl_CooperativeMatrixLayoutRowMajor);
#else
            // fp16p sfp is uint, fix offset
            coopMatLoad(bias, C_blob_data, ((wgni * UNROLL_WG_N + sgni) * UNROLL_SG_N + zn) * N / 2, 0, gl_CooperativeMatrixLayoutRowMajor);
#endif
#elif ncnn_VK_NV_cooperative_matrix
            fcoopmatNV<16, gl_ScopeSubgroup, M, N> bias;
#if NCNN_fp16_storage
            coopMatLoadNV(bias, C_blob_data, ((wgni * UNROLL_WG_N + sgni) * UNROLL_SG_N + zn) * N, 0, false);
#else
            // fp16p sfp is uint, fix offset
            coopMatLoadNV(bias, C_blob_data, ((wgni * UNROLL_WG_N + sgni) * UNROLL_SG_N + zn) * N / 2, 0, false);
#endif
#endif

            [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
            {
#if NCNN_fp16_arithmetic
                sum[zn][zm] = bias;
#else
#if ncnn_VK_KHR_cooperative_matrix
                sum[zn][zm] = coopmat<float, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(bias);
#elif ncnn_VK_NV_cooperative_matrix
                sum[zn][zm] = fcoopmatNV<32, gl_ScopeSubgroup, M, N>(bias);
#endif
#endif
            }
        }
    }

    if (beta != 1.f)
    {
        [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
        {
            [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
            {
                sum[zn][zm] = sum[zn][zm] * afp(beta);
            }
        }
    }

    uint k = 0;

    if (kk >= UNROLL_SG_K * 2)
    {
        // local stack and shared memory ping-pong

        // prefetch
        uvec2 prefetch_tmp_a[(UNROLL_SG_M * UNROLL_SG_K * M * K / 4 + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N)];
        uvec2 prefetch_tmp_b[(UNROLL_SG_N * UNROLL_SG_K * K * N / 4 + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M)];

        // prefetch the very first
        {
            const uint ki = 0;

            // load A
            if (transA == 0)
            {
                if (psc(A_elempack) == 1)
                {
                    //        +-K-+
                    //        M   |
                    //        +- -+
                    //      SG_UM |
                    //     ^  +---+
                    //     |  |   |
                    //   SG_UK+- -+
                    //     |  |   |
                    //   ^ v  +---+
                    //   |    |   |
                    //   |    +- -+
                    //   |    |   |
                    // WG_UM  +---+
                    //   |    |   |
                    //   |    +- -+
                    //   |    |   |
                    //   v    +---+

                    const uint Kd4_M_USGM_USGK = Kd4 * M * UNROLL_SG_M * UNROLL_SG_K;
                    const uint Kd4_M_USGM_USGK_d_subgroupsize = (Kd4_M_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                    [[unroll]] for (uint q = 0; q < Kd4_M_USGM_USGK_d_subgroupsize; q++)
                    {
                        const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                        if (Kd4_M_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Kd4_M_USGM_USGK)
                        {
                            const uint zk = siq / (Kd4 * M * UNROLL_SG_M);
                            const uint zmij = siq % (Kd4 * M * UNROLL_SG_M);
                            const uint zm = zmij / (Kd4 * M);
                            const uint ij = zmij % (Kd4 * M);

                            uvec2 v = uvec2(0);

                            {
                                const uint j = ij / Kd4;
                                const uint i = ij % Kd4;

                                const uint gk = ki / 4 + zk * Kd4 + i;
                                const uint gm = (mi + zm) * M + j;

                                if (gm < psc(GM))
                                {
                                    const uvec4 gk4 = gk * 4 + uvec4(0, 1, 2, 3);

                                    if (p.A_hstep % 4 == 0)
                                    {
                                        const uint ai = gm * (p.A_hstep / 4) + gk;

                                        v = A_blob_data[ai];

                                        uvec4 mask4 = uvec4(lessThan(gk4, uvec4(psc(GK)))) * 0xFFFFu;
                                        uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                        v = v & packed_mask;
                                    }
                                    else
                                    {
                                        vec2 v4a = vec2(0.f);
                                        vec2 v4b = vec2(0.f);

                                        const uvec4 ai4 = gm * p.A_hstep + gk4;
                                        const uvec4 ai4d4 = ai4 / 4;
                                        const uvec4 ai4m4d2 = (ai4 % 4) / 2;
                                        const uvec4 ai4m2 = ai4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                        if (gk4.r < psc(GK)) v4a.r = unpackBFloat2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                        if (gk4.g < psc(GK)) v4a.g = unpackBFloat2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                        if (gk4.b < psc(GK)) v4b.r = unpackBFloat2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                        if (gk4.a < psc(GK)) v4b.g = unpackBFloat2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                        v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                        if (gk4.r < psc(GK)) v4a.r = unpackHalf2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                        if (gk4.g < psc(GK)) v4a.g = unpackHalf2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                        if (gk4.b < psc(GK)) v4b.r = unpackHalf2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                        if (gk4.a < psc(GK)) v4b.g = unpackHalf2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                        v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                    }
                                }
                            }

                            prefetch_tmp_a[q] = v;
                        }
                    }
                }
                else // if (psc(A_elempack) == 4)
                {
                    const uint Md4_K_USGM_USGK = Md4 * K * UNROLL_SG_M * UNROLL_SG_K;
                    const uint Md4_K_USGM_USGK_d_subgroupsize = (Md4_K_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                    [[unroll]] for (uint q = 0; q < Md4_K_USGM_USGK_d_subgroupsize; q++)
                    {
                        const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                        if (Md4_K_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Md4_K_USGM_USGK)
                        {
                            const uint zk = siq / (Md4 * K * UNROLL_SG_M);
                            const uint zmij = siq % (Md4 * K * UNROLL_SG_M);
                            const uint zm = zmij / (Md4 * K);
                            const uint ij = zmij % (Md4 * K);
                            const uint i = ij / Md4;
                            const uint j = ij % Md4;

                            uvec2 v = uvec2(0);

                            const uint gk = ki + zk * K + i;
                            const uint gm = (mi + zm) * Md4 + j;

                            if (gk < psc(GK))
                            {
                                v = A_blob_data[gm * p.A_hstep + gk];
                            }

                            prefetch_tmp_a[q] = v;
                        }
                    }
                }
            }
            else
            {
                if (psc(A_elempack) == 1)
                {
                    //        +-M-+
                    //        K   |
                    //        +SG_UM
                    //        |   |
                    //     ^  +---+
                    //     |  |   |
                    //   SG_UK+- -+
                    //     |  |   |
                    //   ^ v  +---+
                    //   |    |   |
                    //   |    +- -+
                    //   |    |   |
                    // WG_UM  +---+
                    //   |    |   |
                    //   |    +- -+
                    //   |    |   |
                    //   v    +---+

                    const uint Md4_K_USGM_USGK = Md4 * K * UNROLL_SG_M * UNROLL_SG_K;
                    const uint Md4_K_USGM_USGK_d_subgroupsize = (Md4_K_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                    [[unroll]] for (uint q = 0; q < Md4_K_USGM_USGK_d_subgroupsize; q++)
                    {
                        const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                        if (Md4_K_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Md4_K_USGM_USGK)
                        {
                            const uint zk = siq / (Md4 * K * UNROLL_SG_M);
                            const uint zmij = siq % (Md4 * K * UNROLL_SG_M);
                            const uint zm = zmij / (Md4 * K);
                            const uint ij = zmij % (Md4 * K);

                            uvec2 v = uvec2(0);

                            {
                                const uint i = ij / Md4;
                                const uint j = ij % Md4;

                                const uint gk = ki + zk * K + i;
                                const uint gm = (mi + zm) * Md4 + j;

                                if (gk < psc(GK))
                                {
                                    if (p.A_hstep % 4 == 0)
                                    {
                                        const uint ai = gk * (p.A_hstep / 4) + gm;

                                        v = A_blob_data[ai];

                                        uvec4 gm4_vals = gm * 4 + uvec4(0, 1, 2, 3);
                                        uvec4 mask4 = uvec4(lessThan(gm4_vals, uvec4(psc(GM)))) * 0xFFFFu;
                                        uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                        v = v & packed_mask;
                                    }
                                    else
                                    {
                                        const uvec4 gm4 = gm * 4 + uvec4(0, 1, 2, 3);

                                        vec2 v4a = vec2(0.f);
                                        vec2 v4b = vec2(0.f);

                                        const uvec4 ai4 = gk * p.A_hstep + gm4;
                                        const uvec4 ai4d4 = ai4 / 4;
                                        const uvec4 ai4m4d2 = (ai4 % 4) / 2;
                                        const uvec4 ai4m2 = ai4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                        if (gm4.r < psc(GM)) v4a.r = unpackBFloat2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                        if (gm4.g < psc(GM)) v4a.g = unpackBFloat2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                        if (gm4.b < psc(GM)) v4b.r = unpackBFloat2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                        if (gm4.a < psc(GM)) v4b.g = unpackBFloat2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                        v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                        if (gm4.r < psc(GM)) v4a.r = unpackHalf2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                        if (gm4.g < psc(GM)) v4a.g = unpackHalf2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                        if (gm4.b < psc(GM)) v4b.r = unpackHalf2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                        if (gm4.a < psc(GM)) v4b.g = unpackHalf2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                        v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                    }
                                }
                            }

                            prefetch_tmp_a[q] = v;
                        }
                    }
                }
                else // if (psc(A_elempack) == 4)
                {
                    const uint Kd4_M_USGM_USGK = Kd4 * M * UNROLL_SG_M * UNROLL_SG_K;
                    const uint Kd4_M_USGM_USGK_d_subgroupsize = (Kd4_M_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                    [[unroll]] for (uint q = 0; q < Kd4_M_USGM_USGK_d_subgroupsize; q++)
                    {
                        const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                        if (Kd4_M_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Kd4_M_USGM_USGK)
                        {
                            const uint zk = siq / (Kd4 * M * UNROLL_SG_M);
                            const uint zmij = siq % (Kd4 * M * UNROLL_SG_M);
                            const uint zm = zmij / (Kd4 * M);
                            const uint ij = zmij % (Kd4 * M);
                            const uint j = ij / Kd4;
                            const uint i = ij % Kd4;

                            uvec2 v = uvec2(0);

                            const uint gk = ki / 4 + zk * Kd4 + i;
                            const uint gm = (mi + zm) * M + j;

                            if (gm < psc(GM))
                            {
                                v = A_blob_data[gk * p.A_hstep + gm];

                                uvec4 gk4 = gk * 4 + uvec4(0, 1, 2, 3);
                                uvec4 mask4 = uvec4(lessThan(gk4, uvec4(psc(GK)))) * 0xFFFFu;
                                uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                v = v & packed_mask;
                            }

                            prefetch_tmp_a[q] = v;
                        }
                    }
                }
            }

            // load B
            if (transB == 0)
            {
                if (psc(B_elempack) == 1)
                {
                    //        +-N-+
                    //        K   |
                    //        +SG_UN
                    //        |   |
                    //     ^  +---+
                    //     |  |   |
                    //   SG_UK+- -+
                    //     |  |   |
                    //   ^ v  +---+
                    //   |    |   |
                    //   |    +- -+
                    //   |    |   |
                    // WG_UN  +---+
                    //   |    |   |
                    //   |    +- -+
                    //   |    |   |
                    //   v    +---+

                    const uint Nd4_K_USGN_USGK = Nd4 * K * UNROLL_SG_N * UNROLL_SG_K;
                    const uint Nd4_K_USGN_USGK_d_subgroupsize = (Nd4_K_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                    [[unroll]] for (uint q = 0; q < Nd4_K_USGN_USGK_d_subgroupsize; q++)
                    {
                        const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                        if (Nd4_K_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Nd4_K_USGN_USGK)
                        {
                            const uint zk = siq / (Nd4 * K * UNROLL_SG_N);
                            const uint znij = siq % (Nd4 * K * UNROLL_SG_N);
                            const uint zn = znij / (Nd4 * K);
                            const uint ij = znij % (Nd4 * K);

                            uvec2 v = uvec2(0);

                            {
                                const uint i = ij / Nd4;
                                const uint j = ij % Nd4;

                                const uint gk = ki + zk * K + i;
                                const uint gn = (ni + zn) * Nd4 + j;

                                if (gk < psc(GK))
                                {
                                    const uvec4 gn4 = gn * 4 + uvec4(0, 1, 2, 3);

                                    if (p.B_hstep % 4 == 0)
                                    {
                                        const uint bi = gk * (p.B_hstep / 4) + gn;

                                        v = B_blob_data[bi];

                                        uvec4 mask4 = uvec4(lessThan(gn4, uvec4(psc(GN)))) * 0xFFFFu;
                                        uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                        v = v & packed_mask;
                                    }
                                    else
                                    {
                                        vec2 v4a = vec2(0.f);
                                        vec2 v4b = vec2(0.f);

                                        const uvec4 bi4 = gk * p.B_hstep + gn4;
                                        const uvec4 bi4d4 = bi4 / 4;
                                        const uvec4 bi4m4d2 = (bi4 % 4) / 2;
                                        const uvec4 bi4m2 = bi4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                        if (gn4.r < psc(GN)) v4a.r = unpackBFloat2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                        if (gn4.g < psc(GN)) v4a.g = unpackBFloat2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                        if (gn4.b < psc(GN)) v4b.r = unpackBFloat2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                        if (gn4.a < psc(GN)) v4b.g = unpackBFloat2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                        v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                        if (gn4.r < psc(GN)) v4a.r = unpackHalf2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                        if (gn4.g < psc(GN)) v4a.g = unpackHalf2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                        if (gn4.b < psc(GN)) v4b.r = unpackHalf2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                        if (gn4.a < psc(GN)) v4b.g = unpackHalf2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                        v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                    }
                                }
                            }

                            prefetch_tmp_b[q] = v;
                        }
                    }
                }
                else // if (psc(B_elempack) == 4)
                {
                    const uint Kd4_N_USGN_USGK = Kd4 * N * UNROLL_SG_N * UNROLL_SG_K;
                    const uint Kd4_N_USGN_USGK_d_subgroupsize = (Kd4_N_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                    [[unroll]] for (uint q = 0; q < Kd4_N_USGN_USGK_d_subgroupsize; q++)
                    {
                        const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                        if (Kd4_N_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Kd4_N_USGN_USGK)
                        {
                            const uint zk = siq / (Kd4 * N * UNROLL_SG_N);
                            const uint znij = siq % (Kd4 * N * UNROLL_SG_N);
                            const uint zn = znij / (Kd4 * N);
                            const uint ij = znij % (Kd4 * N);

                            uvec2 v = uvec2(0);

                            const uint i = ij / Kd4;
                            const uint j = ij % Kd4;

                            const uint gn = (ni + zn) * N + i;
                            const uint gk = ki / 4 + zk * Kd4 + j;

                            if (gn < psc(GN))
                            {
                                v = B_blob_data[gk * p.B_hstep + gn];
                            }

                            prefetch_tmp_b[q] = v;
                        }
                    }
                }
            }
            else
            {
                if (psc(B_elempack) == 1)
                {
                    //        +-K-+
                    //        N   |
                    //        +SG_UN
                    //        |   |
                    //     ^  +---+
                    //     |  |   |
                    //   SG_UK+- -+
                    //     |  |   |
                    //   ^ v  +---+
                    //   |    |   |
                    //   |    +- -+
                    //   |    |   |
                    // WG_UN  +---+
                    //   |    |   |
                    //   |    +- -+
                    //   |    |   |
                    //   v    +---+

                    const uint Kd4_N_USGN_USGK = Kd4 * N * UNROLL_SG_N * UNROLL_SG_K;
                    const uint Kd4_N_USGN_USGK_d_subgroupsize = (Kd4_N_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                    [[unroll]] for (uint q = 0; q < Kd4_N_USGN_USGK_d_subgroupsize; q++)
                    {
                        const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                        if (Kd4_N_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Kd4_N_USGN_USGK)
                        {
                            const uint zk = siq / (Kd4 * N * UNROLL_SG_N);
                            const uint znij = siq % (Kd4 * N * UNROLL_SG_N);
                            const uint zn = znij / (Kd4 * N);
                            const uint ij = znij % (Kd4 * N);

                            uvec2 v = uvec2(0);

                            {
                                const uint j = ij / Kd4;
                                const uint i = ij % Kd4;

                                const uint gk = ki / 4 + zk * Kd4 + i;
                                const uint gn = (ni + zn) * N + j;

                                if (gn < psc(GN))
                                {
                                    const uvec4 gk4 = gk * 4 + uvec4(0, 1, 2, 3);

                                    if (p.B_hstep % 4 == 0)
                                    {
                                        const uint bi = gn * (p.B_hstep / 4) + gk;

                                        v = B_blob_data[bi];

                                        uvec4 mask4 = uvec4(lessThan(gk4, uvec4(psc(GK)))) * 0xFFFFu;
                                        uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                        v = v & packed_mask;
                                    }
                                    else
                                    {
                                        vec2 v4a = vec2(0.f);
                                        vec2 v4b = vec2(0.f);

                                        const uvec4 bi4 = gn * p.B_hstep + gk4;
                                        const uvec4 bi4d4 = bi4 / 4;
                                        const uvec4 bi4m4d2 = (bi4 % 4) / 2;
                                        const uvec4 bi4m2 = bi4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                        if (gk4.r < psc(GK)) v4a.r = unpackBFloat2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                        if (gk4.g < psc(GK)) v4a.g = unpackBFloat2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                        if (gk4.b < psc(GK)) v4b.r = unpackBFloat2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                        if (gk4.a < psc(GK)) v4b.g = unpackBFloat2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                        v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                        if (gk4.r < psc(GK)) v4a.r = unpackHalf2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                        if (gk4.g < psc(GK)) v4a.g = unpackHalf2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                        if (gk4.b < psc(GK)) v4b.r = unpackHalf2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                        if (gk4.a < psc(GK)) v4b.g = unpackHalf2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                        v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                    }
                                }
                            }

                            prefetch_tmp_b[q] = v;
                        }
                    }
                }
                else // if (psc(B_elempack) == 4)
                {
                    const uint Nd4_K_USGN_USGK = Nd4 * K * UNROLL_SG_N * UNROLL_SG_K;
                    const uint Nd4_K_USGN_USGK_d_subgroupsize = (Nd4_K_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                    [[unroll]] for (uint q = 0; q < Nd4_K_USGN_USGK_d_subgroupsize; q++)
                    {
                        const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                        if (Nd4_K_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Nd4_K_USGN_USGK)
                        {
                            const uint zk = siq / (Nd4 * K * UNROLL_SG_N);
                            const uint znij = siq % (Nd4 * K * UNROLL_SG_N);
                            const uint zn = znij / (Nd4 * K);
                            const uint ij = znij % (Nd4 * K);
                            const uint j = ij / Nd4;
                            const uint i = ij % Nd4;

                            uvec2 v = uvec2(0);

                            const uint gk = ki + zk * K + j;
                            const uint gn = (ni + zn) * Nd4 + i;

                            if (gk < psc(GK))
                            {
                                v = B_blob_data[gn * p.B_hstep + gk];
                            }

                            prefetch_tmp_b[q] = v;
                        }
                    }
                }
            }
        }

        k += UNROLL_SG_K;

        for (; k + UNROLL_SG_K - 1 < kk; k += UNROLL_SG_K)
        {
            barrier();

            // copy prefetch to shared memory
            {
                // load A
                if (transA == 0)
                {
                    const uint Kd4_M_USGM_USGK = Kd4 * M * UNROLL_SG_M * UNROLL_SG_K;
                    const uint Kd4_M_USGM_USGK_d_subgroupsize = (Kd4_M_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                    [[unroll]] for (uint q = 0; q < Kd4_M_USGM_USGK_d_subgroupsize; q++)
                    {
                        const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                        if (Kd4_M_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Kd4_M_USGM_USGK)
                        {
                            if (psc(A_elempack) == 4)
                            {
                                const uint i = siq / Md4;
                                const uint j = siq % Md4;

                                tmp_a[(sgmi * UNROLL_SG_K * UNROLL_SG_M * K + i) * Md4p + j] = prefetch_tmp_a[q];
                            }
                            else
                            {
                                const uint j = siq / Kd4;
                                const uint i = siq % Kd4;

                                tmp_a[(sgmi * UNROLL_SG_K * UNROLL_SG_M * M + j) * Kd4p + i] = prefetch_tmp_a[q];
                            }
                        }
                    }
                }
                else
                {
                    const uint Md4_K_USGM_USGK = Md4 * K * UNROLL_SG_M * UNROLL_SG_K;
                    const uint Md4_K_USGM_USGK_d_subgroupsize = (Md4_K_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                    [[unroll]] for (uint q = 0; q < Md4_K_USGM_USGK_d_subgroupsize; q++)
                    {
                        const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                        if (Md4_K_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Md4_K_USGM_USGK)
                        {
                            if (psc(A_elempack) == 4)
                            {
                                const uint j = siq / Kd4;
                                const uint i = siq % Kd4;

                                tmp_a[(sgmi * UNROLL_SG_K * UNROLL_SG_M * M + j) * Kd4p + i] = prefetch_tmp_a[q];
                            }
                            else
                            {
                                const uint i = siq / Md4;
                                const uint j = siq % Md4;

                                tmp_a[(sgmi * UNROLL_SG_K * UNROLL_SG_M * K + i) * Md4p + j] = prefetch_tmp_a[q];
                            }
                        }
                    }
                }

                // load B
                if (transB == 0)
                {
                    const uint Nd4_K_USGN_USGK = Nd4 * K * UNROLL_SG_N * UNROLL_SG_K;
                    const uint Nd4_K_USGN_USGK_d_subgroupsize = (Nd4_K_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                    [[unroll]] for (uint q = 0; q < Nd4_K_USGN_USGK_d_subgroupsize; q++)
                    {
                        const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                        if (Nd4_K_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Nd4_K_USGN_USGK)
                        {
                            if (psc(B_elempack) == 4)
                            {
                                const uint i = siq / Kd4;
                                const uint j = siq % Kd4;

                                tmp_b[(sgni * UNROLL_SG_K * UNROLL_SG_N * N + i) * Kd4p + j] = prefetch_tmp_b[q];
                            }
                            else
                            {
                                const uint i = siq / Nd4;
                                const uint j = siq % Nd4;

                                tmp_b[(sgni * UNROLL_SG_K * UNROLL_SG_N * K + i) * Nd4p + j] = prefetch_tmp_b[q];
                            }
                        }
                    }
                }
                else
                {
                    const uint Kd4_N_USGN_USGK = Kd4 * N * UNROLL_SG_N * UNROLL_SG_K;
                    const uint Kd4_N_USGN_USGK_d_subgroupsize = (Kd4_N_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                    [[unroll]] for (uint q = 0; q < Kd4_N_USGN_USGK_d_subgroupsize; q++)
                    {
                        const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                        if (Kd4_N_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Kd4_N_USGN_USGK)
                        {
                            if (psc(B_elempack) == 4)
                            {
                                const uint j = siq / Nd4;
                                const uint i = siq % Nd4;

                                tmp_b[(sgni * UNROLL_SG_K * UNROLL_SG_N * K + j) * Nd4p + i] = prefetch_tmp_b[q];
                            }
                            else
                            {
                                const uint j = siq / Kd4;
                                const uint i = siq % Kd4;

                                tmp_b[(sgni * UNROLL_SG_K * UNROLL_SG_N * N + j) * Kd4p + i] = prefetch_tmp_b[q];
                            }
                        }
                    }
                }
            }

            barrier();

            // prefetch the next
            {
                const uint ki = k * K;

                // load A
                if (transA == 0)
                {
                    if (psc(A_elempack) == 1)
                    {
                        //        +-K-+
                        //        M   |
                        //        +- -+
                        //      SG_UM |
                        //     ^  +---+
                        //     |  |   |
                        //   SG_UK+- -+
                        //     |  |   |
                        //   ^ v  +---+
                        //   |    |   |
                        //   |    +- -+
                        //   |    |   |
                        // WG_UM  +---+
                        //   |    |   |
                        //   |    +- -+
                        //   |    |   |
                        //   v    +---+

                        const uint Kd4_M_USGM_USGK = Kd4 * M * UNROLL_SG_M * UNROLL_SG_K;
                        const uint Kd4_M_USGM_USGK_d_subgroupsize = (Kd4_M_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                        [[unroll]] for (uint q = 0; q < Kd4_M_USGM_USGK_d_subgroupsize; q++)
                        {
                            const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                            if (Kd4_M_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Kd4_M_USGM_USGK)
                            {
                                const uint zk = siq / (Kd4 * M * UNROLL_SG_M);
                                const uint zmij = siq % (Kd4 * M * UNROLL_SG_M);
                                const uint zm = zmij / (Kd4 * M);
                                const uint ij = zmij % (Kd4 * M);

                                uvec2 v = uvec2(0);

                                {
                                    const uint j = ij / Kd4;
                                    const uint i = ij % Kd4;

                                    const uint gk = ki / 4 + zk * Kd4 + i;
                                    const uint gm = (mi + zm) * M + j;

                                    if (gm < psc(GM))
                                    {
                                        const uvec4 gk4 = gk * 4 + uvec4(0, 1, 2, 3);

                                        if (p.A_hstep % 4 == 0)
                                        {
                                            const uint ai = gm * (p.A_hstep / 4) + gk;

                                            v = A_blob_data[ai];

                                            uvec4 mask4 = uvec4(lessThan(gk4, uvec4(psc(GK)))) * 0xFFFFu;
                                            uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                            v = v & packed_mask;
                                        }
                                        else
                                        {
                                            vec2 v4a = vec2(0.f);
                                            vec2 v4b = vec2(0.f);

                                            const uvec4 ai4 = gm * p.A_hstep + gk4;
                                            const uvec4 ai4d4 = ai4 / 4;
                                            const uvec4 ai4m4d2 = (ai4 % 4) / 2;
                                            const uvec4 ai4m2 = ai4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                            if (gk4.r < psc(GK)) v4a.r = unpackBFloat2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                            if (gk4.g < psc(GK)) v4a.g = unpackBFloat2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                            if (gk4.b < psc(GK)) v4b.r = unpackBFloat2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                            if (gk4.a < psc(GK)) v4b.g = unpackBFloat2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                            v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                            if (gk4.r < psc(GK)) v4a.r = unpackHalf2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                            if (gk4.g < psc(GK)) v4a.g = unpackHalf2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                            if (gk4.b < psc(GK)) v4b.r = unpackHalf2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                            if (gk4.a < psc(GK)) v4b.g = unpackHalf2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                            v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                        }
                                    }
                                }

                                prefetch_tmp_a[q] = v;
                            }
                        }
                    }
                    else // if (psc(A_elempack) == 4)
                    {
                        const uint Md4_K_USGM_USGK = Md4 * K * UNROLL_SG_M * UNROLL_SG_K;
                        const uint Md4_K_USGM_USGK_d_subgroupsize = (Md4_K_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                        [[unroll]] for (uint q = 0; q < Md4_K_USGM_USGK_d_subgroupsize; q++)
                        {
                            const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                            if (Md4_K_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Md4_K_USGM_USGK)
                            {
                                const uint zk = siq / (Md4 * K * UNROLL_SG_M);
                                const uint zmij = siq % (Md4 * K * UNROLL_SG_M);
                                const uint zm = zmij / (Md4 * K);
                                const uint ij = zmij % (Md4 * K);
                                const uint i = ij / Md4;
                                const uint j = ij % Md4;

                                uvec2 v = uvec2(0);

                                const uint gk = ki + zk * K + i;
                                const uint gm = (mi + zm) * Md4 + j;

                                if (gk < psc(GK))
                                {
                                    v = A_blob_data[gm * p.A_hstep + gk];
                                }

                                prefetch_tmp_a[q] = v;
                            }
                        }
                    }
                }
                else
                {
                    if (psc(A_elempack) == 1)
                    {
                        //        +-M-+
                        //        K   |
                        //        +SG_UM
                        //        |   |
                        //     ^  +---+
                        //     |  |   |
                        //   SG_UK+- -+
                        //     |  |   |
                        //   ^ v  +---+
                        //   |    |   |
                        //   |    +- -+
                        //   |    |   |
                        // WG_UM  +---+
                        //   |    |   |
                        //   |    +- -+
                        //   |    |   |
                        //   v    +---+

                        const uint Md4_K_USGM_USGK = Md4 * K * UNROLL_SG_M * UNROLL_SG_K;
                        const uint Md4_K_USGM_USGK_d_subgroupsize = (Md4_K_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                        [[unroll]] for (uint q = 0; q < Md4_K_USGM_USGK_d_subgroupsize; q++)
                        {
                            const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                            if (Md4_K_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Md4_K_USGM_USGK)
                            {
                                const uint zk = siq / (Md4 * K * UNROLL_SG_M);
                                const uint zmij = siq % (Md4 * K * UNROLL_SG_M);
                                const uint zm = zmij / (Md4 * K);
                                const uint ij = zmij % (Md4 * K);

                                uvec2 v = uvec2(0);

                                {
                                    const uint i = ij / Md4;
                                    const uint j = ij % Md4;

                                    const uint gk = ki + zk * K + i;
                                    const uint gm = (mi + zm) * Md4 + j;

                                    if (gk < psc(GK))
                                    {
                                        if (p.A_hstep % 4 == 0)
                                        {
                                            const uint ai = gk * (p.A_hstep / 4) + gm;

                                            v = A_blob_data[ai];

                                            uvec4 gm4_vals = gm * 4 + uvec4(0, 1, 2, 3);
                                            uvec4 mask4 = uvec4(lessThan(gm4_vals, uvec4(psc(GM)))) * 0xFFFFu;
                                            uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                            v = v & packed_mask;
                                        }
                                        else
                                        {
                                            const uvec4 gm4 = gm * 4 + uvec4(0, 1, 2, 3);

                                            vec2 v4a = vec2(0.f);
                                            vec2 v4b = vec2(0.f);

                                            const uvec4 ai4 = gk * p.A_hstep + gm4;
                                            const uvec4 ai4d4 = ai4 / 4;
                                            const uvec4 ai4m4d2 = (ai4 % 4) / 2;
                                            const uvec4 ai4m2 = ai4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                            if (gm4.r < psc(GM)) v4a.r = unpackBFloat2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                            if (gm4.g < psc(GM)) v4a.g = unpackBFloat2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                            if (gm4.b < psc(GM)) v4b.r = unpackBFloat2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                            if (gm4.a < psc(GM)) v4b.g = unpackBFloat2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                            v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                            if (gm4.r < psc(GM)) v4a.r = unpackHalf2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                            if (gm4.g < psc(GM)) v4a.g = unpackHalf2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                            if (gm4.b < psc(GM)) v4b.r = unpackHalf2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                            if (gm4.a < psc(GM)) v4b.g = unpackHalf2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                            v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                        }
                                    }
                                }

                                prefetch_tmp_a[q] = v;
                            }
                        }
                    }
                    else // if (psc(A_elempack) == 4)
                    {
                        const uint Kd4_M_USGM_USGK = Kd4 * M * UNROLL_SG_M * UNROLL_SG_K;
                        const uint Kd4_M_USGM_USGK_d_subgroupsize = (Kd4_M_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                        [[unroll]] for (uint q = 0; q < Kd4_M_USGM_USGK_d_subgroupsize; q++)
                        {
                            const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                            if (Kd4_M_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Kd4_M_USGM_USGK)
                            {
                                const uint zk = siq / (Kd4 * M * UNROLL_SG_M);
                                const uint zmij = siq % (Kd4 * M * UNROLL_SG_M);
                                const uint zm = zmij / (Kd4 * M);
                                const uint ij = zmij % (Kd4 * M);
                                const uint j = ij / Kd4;
                                const uint i = ij % Kd4;

                                uvec2 v = uvec2(0);

                                const uint gk = ki / 4 + zk * Kd4 + i;
                                const uint gm = (mi + zm) * M + j;

                                if (gm < psc(GM))
                                {
                                    v = A_blob_data[gk * p.A_hstep + gm];

                                    uvec4 gk4 = gk * 4 + uvec4(0, 1, 2, 3);
                                    uvec4 mask4 = uvec4(lessThan(gk4, uvec4(psc(GK)))) * 0xFFFFu;
                                    uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                    v = v & packed_mask;
                                }

                                prefetch_tmp_a[q] = v;
                            }
                        }
                    }
                }

                // load B
                if (transB == 0)
                {
                    if (psc(B_elempack) == 1)
                    {
                        //        +-N-+
                        //        K   |
                        //        +SG_UN
                        //        |   |
                        //     ^  +---+
                        //     |  |   |
                        //   SG_UK+- -+
                        //     |  |   |
                        //   ^ v  +---+
                        //   |    |   |
                        //   |    +- -+
                        //   |    |   |
                        // WG_UN  +---+
                        //   |    |   |
                        //   |    +- -+
                        //   |    |   |
                        //   v    +---+

                        const uint Nd4_K_USGN_USGK = Nd4 * K * UNROLL_SG_N * UNROLL_SG_K;
                        const uint Nd4_K_USGN_USGK_d_subgroupsize = (Nd4_K_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                        [[unroll]] for (uint q = 0; q < Nd4_K_USGN_USGK_d_subgroupsize; q++)
                        {
                            const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                            if (Nd4_K_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Nd4_K_USGN_USGK)
                            {
                                const uint zk = siq / (Nd4 * K * UNROLL_SG_N);
                                const uint znij = siq % (Nd4 * K * UNROLL_SG_N);
                                const uint zn = znij / (Nd4 * K);
                                const uint ij = znij % (Nd4 * K);

                                uvec2 v = uvec2(0);

                                {
                                    const uint i = ij / Nd4;
                                    const uint j = ij % Nd4;

                                    const uint gk = ki + zk * K + i;
                                    const uint gn = (ni + zn) * Nd4 + j;

                                    if (gk < psc(GK))
                                    {
                                        const uvec4 gn4 = gn * 4 + uvec4(0, 1, 2, 3);

                                        if (p.B_hstep % 4 == 0)
                                        {
                                            const uint bi = gk * (p.B_hstep / 4) + gn;

                                            v = B_blob_data[bi];

                                            uvec4 mask4 = uvec4(lessThan(gn4, uvec4(psc(GN)))) * 0xFFFFu;
                                            uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                            v = v & packed_mask;
                                        }
                                        else
                                        {
                                            vec2 v4a = vec2(0.f);
                                            vec2 v4b = vec2(0.f);

                                            const uvec4 bi4 = gk * p.B_hstep + gn4;
                                            const uvec4 bi4d4 = bi4 / 4;
                                            const uvec4 bi4m4d2 = (bi4 % 4) / 2;
                                            const uvec4 bi4m2 = bi4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                            if (gn4.r < psc(GN)) v4a.r = unpackBFloat2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                            if (gn4.g < psc(GN)) v4a.g = unpackBFloat2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                            if (gn4.b < psc(GN)) v4b.r = unpackBFloat2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                            if (gn4.a < psc(GN)) v4b.g = unpackBFloat2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                            v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                            if (gn4.r < psc(GN)) v4a.r = unpackHalf2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                            if (gn4.g < psc(GN)) v4a.g = unpackHalf2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                            if (gn4.b < psc(GN)) v4b.r = unpackHalf2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                            if (gn4.a < psc(GN)) v4b.g = unpackHalf2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                            v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                        }
                                    }
                                }

                                prefetch_tmp_b[q] = v;
                            }
                        }
                    }
                    else // if (psc(B_elempack) == 4)
                    {
                        const uint Kd4_N_USGN_USGK = Kd4 * N * UNROLL_SG_N * UNROLL_SG_K;
                        const uint Kd4_N_USGN_USGK_d_subgroupsize = (Kd4_N_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                        [[unroll]] for (uint q = 0; q < Kd4_N_USGN_USGK_d_subgroupsize; q++)
                        {
                            const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                            if (Kd4_N_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Kd4_N_USGN_USGK)
                            {
                                const uint zk = siq / (Kd4 * N * UNROLL_SG_N);
                                const uint znij = siq % (Kd4 * N * UNROLL_SG_N);
                                const uint zn = znij / (Kd4 * N);
                                const uint ij = znij % (Kd4 * N);
                                const uint i = ij / Kd4;
                                const uint j = ij % Kd4;

                                uvec2 v = uvec2(0);

                                const uint gn = (ni + zn) * N + i;
                                const uint gk = ki / 4 + zk * Kd4 + j;

                                if (gn < psc(GN))
                                {
                                    v = B_blob_data[gk * p.B_hstep + gn];
                                }

                                prefetch_tmp_b[q] = v;
                            }
                        }
                    }
                }
                else
                {
                    if (psc(B_elempack) == 1)
                    {
                        //        +-K-+
                        //        N   |
                        //        +SG_UN
                        //        |   |
                        //     ^  +---+
                        //     |  |   |
                        //   SG_UK+- -+
                        //     |  |   |
                        //   ^ v  +---+
                        //   |    |   |
                        //   |    +- -+
                        //   |    |   |
                        // WG_UN  +---+
                        //   |    |   |
                        //   |    +- -+
                        //   |    |   |
                        //   v    +---+

                        const uint Kd4_N_USGN_USGK = Kd4 * N * UNROLL_SG_N * UNROLL_SG_K;
                        const uint Kd4_N_USGN_USGK_d_subgroupsize = (Kd4_N_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                        [[unroll]] for (uint q = 0; q < Kd4_N_USGN_USGK_d_subgroupsize; q++)
                        {
                            const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                            if (Kd4_N_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Kd4_N_USGN_USGK)
                            {
                                const uint zk = siq / (Kd4 * N * UNROLL_SG_N);
                                const uint znij = siq % (Kd4 * N * UNROLL_SG_N);
                                const uint zn = znij / (Kd4 * N);
                                const uint ij = znij % (Kd4 * N);

                                uvec2 v = uvec2(0);

                                {
                                    const uint j = ij / Kd4;
                                    const uint i = ij % Kd4;

                                    const uint gk = ki / 4 + zk * Kd4 + i;
                                    const uint gn = (ni + zn) * N + j;

                                    if (gn < psc(GN))
                                    {
                                        const uvec4 gk4 = gk * 4 + uvec4(0, 1, 2, 3);

                                        if (p.B_hstep % 4 == 0)
                                        {
                                            const uint bi = gn * (p.B_hstep / 4) + gk;

                                            v = B_blob_data[bi];

                                            uvec4 mask4 = uvec4(lessThan(gk4, uvec4(psc(GK)))) * 0xFFFFu;
                                            uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                            v = v & packed_mask;
                                        }
                                        else
                                        {
                                            vec2 v4a = vec2(0.f);
                                            vec2 v4b = vec2(0.f);

                                            const uvec4 bi4 = gn * p.B_hstep + gk4;
                                            const uvec4 bi4d4 = bi4 / 4;
                                            const uvec4 bi4m4d2 = (bi4 % 4) / 2;
                                            const uvec4 bi4m2 = bi4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                            if (gk4.r < psc(GK)) v4a.r = unpackBFloat2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                            if (gk4.g < psc(GK)) v4a.g = unpackBFloat2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                            if (gk4.b < psc(GK)) v4b.r = unpackBFloat2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                            if (gk4.a < psc(GK)) v4b.g = unpackBFloat2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                            v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                            if (gk4.r < psc(GK)) v4a.r = unpackHalf2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                            if (gk4.g < psc(GK)) v4a.g = unpackHalf2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                            if (gk4.b < psc(GK)) v4b.r = unpackHalf2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                            if (gk4.a < psc(GK)) v4b.g = unpackHalf2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                            v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                        }
                                    }
                                }

                                prefetch_tmp_b[q] = v;
                            }
                        }
                    }
                    else // if (psc(B_elempack) == 4)
                    {
                        const uint Nd4_K_USGN_USGK = Nd4 * K * UNROLL_SG_N * UNROLL_SG_K;
                        const uint Nd4_K_USGN_USGK_d_subgroupsize = (Nd4_K_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                        [[unroll]] for (uint q = 0; q < Nd4_K_USGN_USGK_d_subgroupsize; q++)
                        {
                            const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                            if (Nd4_K_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Nd4_K_USGN_USGK)
                            {
                                const uint zk = siq / (Nd4 * K * UNROLL_SG_N);
                                const uint znij = siq % (Nd4 * K * UNROLL_SG_N);
                                const uint zn = znij / (Nd4 * K);
                                const uint ij = znij % (Nd4 * K);
                                const uint j = ij / Nd4;
                                const uint i = ij % Nd4;

                                uvec2 v = uvec2(0);

                                const uint gk = ki + zk * K + j;
                                const uint gn = (ni + zn) * Nd4 + i;

                                if (gk < psc(GK))
                                {
                                    v = B_blob_data[gn * p.B_hstep + gk];
                                }

                                prefetch_tmp_b[q] = v;
                            }
                        }
                    }
                }
            }

#if ncnn_VK_KHR_cooperative_matrix
#if NCNN_bf16_storage || NCNN_bf16_packed
            coopmat<bfloat16_t, gl_ScopeSubgroup, M, K, gl_MatrixUseA> A[UNROLL_SG_M];
            coopmat<bfloat16_t, gl_ScopeSubgroup, K, N, gl_MatrixUseB> B[UNROLL_SG_N];
#else
            coopmat<float16_t, gl_ScopeSubgroup, M, K, gl_MatrixUseA> A[UNROLL_SG_M];
            coopmat<float16_t, gl_ScopeSubgroup, K, N, gl_MatrixUseB> B[UNROLL_SG_N];
#endif
#elif ncnn_VK_NV_cooperative_matrix
            fcoopmatNV<16, gl_ScopeSubgroup, M, K> A[UNROLL_SG_M];
            fcoopmatNV<16, gl_ScopeSubgroup, K, N> B[UNROLL_SG_N];
#endif

            [[unroll]] for (uint zk = 0; zk < UNROLL_SG_K; zk++)
            {
                [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
                {
                    if (transA == 0)
                    {
                        if (psc(A_elempack) == 4)
                        {
#if ncnn_VK_KHR_cooperative_matrix
                            coopMatLoad(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Md4p * K), Md4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                            coopMatLoadNV(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Md4p * K), Md4p, true);
#endif
                        }
                        else
                        {
#if ncnn_VK_KHR_cooperative_matrix
                            coopMatLoad(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                            coopMatLoadNV(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, false);
#endif
                        }
                    }
                    else
                    {
                        if (psc(A_elempack) == 4)
                        {
#if ncnn_VK_KHR_cooperative_matrix
                            coopMatLoad(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                            coopMatLoadNV(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, false);
#endif
                        }
                        else
                        {
#if ncnn_VK_KHR_cooperative_matrix
                            coopMatLoad(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Md4p * K), Md4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                            coopMatLoadNV(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Md4p * K), Md4p, true);
#endif
                        }
                    }
                }

                [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
                {
                    if (transB == 0)
                    {
                        if (psc(B_elempack) == 4)
                        {
#if ncnn_VK_KHR_cooperative_matrix
                            coopMatLoad(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                            coopMatLoadNV(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, true);
#endif
                        }
                        else
                        {
#if ncnn_VK_KHR_cooperative_matrix
                            coopMatLoad(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                            coopMatLoadNV(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, false);
#endif
                        }
                    }
                    else
                    {
                        if (psc(B_elempack) == 4)
                        {
#if ncnn_VK_KHR_cooperative_matrix
                            coopMatLoad(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                            coopMatLoadNV(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, false);
#endif
                        }
                        else
                        {
#if ncnn_VK_KHR_cooperative_matrix
                            coopMatLoad(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                            coopMatLoadNV(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, true);
#endif
                        }
                    }
                }

                // sum += k * v
                [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
                {
                    [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        sum[zn][zm] = coopMatMulAdd(A[zm], B[zn], sum[zn][zm]);
#elif ncnn_VK_NV_cooperative_matrix
                        sum[zn][zm] = coopMatMulAddNV(A[zm], B[zn], sum[zn][zm]);
#endif
                    }
                }
            }
        }

        barrier();

        // the last copy prefetch to shared memory
        {
            if (transA == 0)
            {
                const uint Kd4_M_USGM_USGK = Kd4 * M * UNROLL_SG_M * UNROLL_SG_K;
                const uint Kd4_M_USGM_USGK_d_subgroupsize = (Kd4_M_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                [[unroll]] for (uint q = 0; q < Kd4_M_USGM_USGK_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                    if (Kd4_M_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Kd4_M_USGM_USGK)
                    {
                        if (psc(A_elempack) == 4)
                        {
                            const uint i = siq / Md4;
                            const uint j = siq % Md4;

                            tmp_a[(sgmi * UNROLL_SG_K * UNROLL_SG_M * K + i) * Md4p + j] = prefetch_tmp_a[q];
                        }
                        else
                        {
                            const uint j = siq / Kd4;
                            const uint i = siq % Kd4;

                            tmp_a[(sgmi * UNROLL_SG_K * UNROLL_SG_M * M + j) * Kd4p + i] = prefetch_tmp_a[q];
                        }
                    }
                }
            }
            else
            {
                const uint Md4_K_USGM_USGK = Md4 * K * UNROLL_SG_M * UNROLL_SG_K;
                const uint Md4_K_USGM_USGK_d_subgroupsize = (Md4_K_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                [[unroll]] for (uint q = 0; q < Md4_K_USGM_USGK_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                    if (Md4_K_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Md4_K_USGM_USGK)
                    {
                        if (psc(A_elempack) == 4)
                        {
                            const uint j = siq / Kd4;
                            const uint i = siq % Kd4;

                            tmp_a[(sgmi * UNROLL_SG_K * UNROLL_SG_M * M + j) * Kd4p + i] = prefetch_tmp_a[q];
                        }
                        else
                        {
                            const uint i = siq / Md4;
                            const uint j = siq % Md4;

                            tmp_a[(sgmi * UNROLL_SG_K * UNROLL_SG_M * K + i) * Md4p + j] = prefetch_tmp_a[q];
                        }
                    }
                }
            }

            // load B
            if (transB == 0)
            {
                const uint Nd4_K_USGN_USGK = Nd4 * K * UNROLL_SG_N * UNROLL_SG_K;
                const uint Nd4_K_USGN_USGK_d_subgroupsize = (Nd4_K_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                [[unroll]] for (uint q = 0; q < Nd4_K_USGN_USGK_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                    if (Nd4_K_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Nd4_K_USGN_USGK)
                    {
                        if (psc(B_elempack) == 4)
                        {
                            const uint i = siq / Kd4;
                            const uint j = siq % Kd4;

                            tmp_b[(sgni * UNROLL_SG_K * UNROLL_SG_N * N + i) * Kd4p + j] = prefetch_tmp_b[q];
                        }
                        else
                        {
                            const uint i = siq / Nd4;
                            const uint j = siq % Nd4;

                            tmp_b[(sgni * UNROLL_SG_K * UNROLL_SG_N * K + i) * Nd4p + j] = prefetch_tmp_b[q];
                        }
                    }
                }
            }
            else
            {
                const uint Kd4_N_USGN_USGK = Kd4 * N * UNROLL_SG_N * UNROLL_SG_K;
                const uint Kd4_N_USGN_USGK_d_subgroupsize = (Kd4_N_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                [[unroll]] for (uint q = 0; q < Kd4_N_USGN_USGK_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                    if (Kd4_N_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Kd4_N_USGN_USGK)
                    {
                        if (psc(B_elempack) == 4)
                        {
                            const uint j = siq / Nd4;
                            const uint i = siq % Nd4;

                            tmp_b[(sgni * UNROLL_SG_K * UNROLL_SG_N * K + j) * Nd4p + i] = prefetch_tmp_b[q];
                        }
                        else
                        {
                            const uint j = siq / Kd4;
                            const uint i = siq % Kd4;

                            tmp_b[(sgni * UNROLL_SG_K * UNROLL_SG_N * N + j) * Kd4p + i] = prefetch_tmp_b[q];
                        }
                    }
                }
            }
        }

        barrier();

#if ncnn_VK_KHR_cooperative_matrix
#if NCNN_bf16_storage || NCNN_bf16_packed
        coopmat<bfloat16_t, gl_ScopeSubgroup, M, K, gl_MatrixUseA> A[UNROLL_SG_M];
        coopmat<bfloat16_t, gl_ScopeSubgroup, K, N, gl_MatrixUseB> B[UNROLL_SG_N];
#else
        coopmat<float16_t, gl_ScopeSubgroup, M, K, gl_MatrixUseA> A[UNROLL_SG_M];
        coopmat<float16_t, gl_ScopeSubgroup, K, N, gl_MatrixUseB> B[UNROLL_SG_N];
#endif
#elif ncnn_VK_NV_cooperative_matrix
        fcoopmatNV<16, gl_ScopeSubgroup, M, K> A[UNROLL_SG_M];
        fcoopmatNV<16, gl_ScopeSubgroup, K, N> B[UNROLL_SG_N];
#endif

        [[unroll]] for (uint zk = 0; zk < UNROLL_SG_K; zk++)
        {
            [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
            {
                if (transA == 0)
                {
                    if (psc(A_elempack) == 4)
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Md4p * K), Md4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Md4p * K), Md4p, true);
#endif
                    }
                    else
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, false);
#endif
                    }
                }
                else
                {
                    if (psc(A_elempack) == 4)
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, false);
#endif
                    }
                    else
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Md4p * K), Md4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Md4p * K), Md4p, true);
#endif
                    }
                }
            }

            [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
            {
                if (transB == 0)
                {
                    if (psc(B_elempack) == 4)
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, true);
#endif
                    }
                    else
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, false);
#endif
                    }
                }
                else
                {
                    if (psc(B_elempack) == 4)
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, false);
#endif
                    }
                    else
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, true);
#endif
                    }
                }
            }

            // sum += k * v
            [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
            {
                [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
                {
#if ncnn_VK_KHR_cooperative_matrix
                    sum[zn][zm] = coopMatMulAdd(A[zm], B[zn], sum[zn][zm]);
#elif ncnn_VK_NV_cooperative_matrix
                    sum[zn][zm] = coopMatMulAddNV(A[zm], B[zn], sum[zn][zm]);
#endif
                }
            }
        }
    }
    else if (kk >= UNROLL_SG_K)
    {
        // no ping-pong version

        const uint ki = 0;

        // load A
        if (transA == 0)
        {
            if (psc(A_elempack) == 1)
            {
                //        +-K-+
                //        M   |
                //        +- -+
                //      SG_UM |
                //     ^  +---+
                //     |  |   |
                //   SG_UK+- -+
                //     |  |   |
                //   ^ v  +---+
                //   |    |   |
                //   |    +- -+
                //   |    |   |
                // WG_UM  +---+
                //   |    |   |
                //   |    +- -+
                //   |    |   |
                //   v    +---+

                const uint Kd4_M_USGM_USGK = Kd4 * M * UNROLL_SG_M * UNROLL_SG_K;
                const uint Kd4_M_USGM_USGK_d_subgroupsize = (Kd4_M_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                [[unroll]] for (uint q = 0; q < Kd4_M_USGM_USGK_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                    if (Kd4_M_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Kd4_M_USGM_USGK)
                    {
                        const uint zk = siq / (Kd4 * M * UNROLL_SG_M);
                        const uint zmij = siq % (Kd4 * M * UNROLL_SG_M);
                        const uint zm = zmij / (Kd4 * M);
                        const uint ij = zmij % (Kd4 * M);

                        uvec2 v = uvec2(0);

                        {
                            const uint j = ij / Kd4;
                            const uint i = ij % Kd4;

                            const uint gk = ki / 4 + zk * Kd4 + i;
                            const uint gm = (mi + zm) * M + j;

                            if (gm < psc(GM))
                            {
                                const uvec4 gk4 = gk * 4 + uvec4(0, 1, 2, 3);

                                if (p.A_hstep % 4 == 0)
                                {
                                    const uint ai = gm * (p.A_hstep / 4) + gk;

                                    v = A_blob_data[ai];

                                    uvec4 mask4 = uvec4(lessThan(gk4, uvec4(psc(GK)))) * 0xFFFFu;
                                    uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                    v = v & packed_mask;
                                }
                                else
                                {
                                    vec2 v4a = vec2(0.f);
                                    vec2 v4b = vec2(0.f);

                                    const uvec4 ai4 = gm * p.A_hstep + gk4;
                                    const uvec4 ai4d4 = ai4 / 4;
                                    const uvec4 ai4m4d2 = (ai4 % 4) / 2;
                                    const uvec4 ai4m2 = ai4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                    if (gk4.r < psc(GK)) v4a.r = unpackBFloat2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                    if (gk4.g < psc(GK)) v4a.g = unpackBFloat2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                    if (gk4.b < psc(GK)) v4b.r = unpackBFloat2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                    if (gk4.a < psc(GK)) v4b.g = unpackBFloat2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                    v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                    if (gk4.r < psc(GK)) v4a.r = unpackHalf2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                    if (gk4.g < psc(GK)) v4a.g = unpackHalf2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                    if (gk4.b < psc(GK)) v4b.r = unpackHalf2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                    if (gk4.a < psc(GK)) v4b.g = unpackHalf2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                    v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                }
                            }

                            tmp_a[(((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * M + j) * Kd4p + i] = v;
                        }
                    }
                }
            }
            else // if (psc(A_elempack) == 4)
            {
                const uint Md4_K_USGM_USGK = Md4 * K * UNROLL_SG_M * UNROLL_SG_K;
                const uint Md4_K_USGM_USGK_d_subgroupsize = (Md4_K_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                [[unroll]] for (uint q = 0; q < Md4_K_USGM_USGK_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                    if (Md4_K_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Md4_K_USGM_USGK)
                    {
                        const uint zk = siq / (Md4 * K * UNROLL_SG_M);
                        const uint zmij = siq % (Md4 * K * UNROLL_SG_M);
                        const uint zm = zmij / (Md4 * K);
                        const uint ij = zmij % (Md4 * K);
                        const uint i = ij / Md4;
                        const uint j = ij % Md4;

                        uvec2 v = uvec2(0);

                        const uint gk = ki + zk * K + i;
                        const uint gm = (mi + zm) * Md4 + j;

                        if (gk < psc(GK))
                        {
                            v = A_blob_data[gm * p.A_hstep + gk];
                        }

                        tmp_a[(((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * K + i) * Md4p + j] = v;
                    }
                }
            }
        }
        else
        {
            if (psc(A_elempack) == 1)
            {
                //        +-M-+
                //        K   |
                //        +SG_UM
                //        |   |
                //     ^  +---+
                //     |  |   |
                //   SG_UK+- -+
                //     |  |   |
                //   ^ v  +---+
                //   |    |   |
                //   |    +- -+
                //   |    |   |
                // WG_UM  +---+
                //   |    |   |
                //   |    +- -+
                //   |    |   |
                //   v    +---+

                const uint Md4_K_USGM_USGK = Md4 * K * UNROLL_SG_M * UNROLL_SG_K;
                const uint Md4_K_USGM_USGK_d_subgroupsize = (Md4_K_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                [[unroll]] for (uint q = 0; q < Md4_K_USGM_USGK_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                    if (Md4_K_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Md4_K_USGM_USGK)
                    {
                        const uint zk = siq / (Md4 * K * UNROLL_SG_M);
                        const uint zmij = siq % (Md4 * K * UNROLL_SG_M);
                        const uint zm = zmij / (Md4 * K);
                        const uint ij = zmij % (Md4 * K);

                        uvec2 v = uvec2(0);

                        {
                            const uint i = ij / Md4;
                            const uint j = ij % Md4;

                            const uint gk = ki + zk * K + i;
                            const uint gm = (mi + zm) * Md4 + j;

                            if (gk < psc(GK))
                            {
                                if (p.A_hstep % 4 == 0)
                                {
                                    const uint ai = gk * (p.A_hstep / 4) + gm;

                                    v = A_blob_data[ai];

                                    uvec4 gm4_vals = gm * 4 + uvec4(0, 1, 2, 3);
                                    uvec4 mask4 = uvec4(lessThan(gm4_vals, uvec4(psc(GM)))) * 0xFFFFu;
                                    uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                    v = v & packed_mask;
                                }
                                else
                                {
                                    const uvec4 gm4 = gm * 4 + uvec4(0, 1, 2, 3);

                                    vec2 v4a = vec2(0.f);
                                    vec2 v4b = vec2(0.f);

                                    const uvec4 ai4 = gk * p.A_hstep + gm4;
                                    const uvec4 ai4d4 = ai4 / 4;
                                    const uvec4 ai4m4d2 = (ai4 % 4) / 2;
                                    const uvec4 ai4m2 = ai4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                    if (gm4.r < psc(GM)) v4a.r = unpackBFloat2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                    if (gm4.g < psc(GM)) v4a.g = unpackBFloat2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                    if (gm4.b < psc(GM)) v4b.r = unpackBFloat2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                    if (gm4.a < psc(GM)) v4b.g = unpackBFloat2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                    v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                    if (gm4.r < psc(GM)) v4a.r = unpackHalf2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                    if (gm4.g < psc(GM)) v4a.g = unpackHalf2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                    if (gm4.b < psc(GM)) v4b.r = unpackHalf2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                    if (gm4.a < psc(GM)) v4b.g = unpackHalf2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                    v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                }
                            }

                            tmp_a[(((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * K + i) * Md4p + j] = v;
                        }
                    }
                }
            }
            else // if (psc(A_elempack) == 4)
            {
                const uint Kd4_M_USGM_USGK = Kd4 * M * UNROLL_SG_M * UNROLL_SG_K;
                const uint Kd4_M_USGM_USGK_d_subgroupsize = (Kd4_M_USGM_USGK + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                [[unroll]] for (uint q = 0; q < Kd4_M_USGM_USGK_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                    if (Kd4_M_USGM_USGK % (subgroup_size * UNROLL_WG_N) == 0 || siq < Kd4_M_USGM_USGK)
                    {
                        const uint zk = siq / (Kd4 * M * UNROLL_SG_M);
                        const uint zmij = siq % (Kd4 * M * UNROLL_SG_M);
                        const uint zm = zmij / (Kd4 * M);
                        const uint ij = zmij % (Kd4 * M);
                        const uint j = ij / Kd4;
                        const uint i = ij % Kd4;

                        uvec2 v = uvec2(0);

                        const uint gk = ki / 4 + zk * Kd4 + i;
                        const uint gm = (mi + zm) * M + j;

                        if (gm < psc(GM))
                        {
                            v = A_blob_data[gk * p.A_hstep + gm];

                            uvec4 gk4 = gk * 4 + uvec4(0, 1, 2, 3);
                            uvec4 mask4 = uvec4(lessThan(gk4, uvec4(psc(GK)))) * 0xFFFFu;
                            uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                            v = v & packed_mask;
                        }

                        tmp_a[(((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * M + j) * Kd4p + i] = v;
                    }
                }
            }
        }

        // load B
        if (transB == 0)
        {
            if (psc(B_elempack) == 1)
            {
                //        +-N-+
                //        K   |
                //        +SG_UN
                //        |   |
                //     ^  +---+
                //     |  |   |
                //   SG_UK+- -+
                //     |  |   |
                //   ^ v  +---+
                //   |    |   |
                //   |    +- -+
                //   |    |   |
                // WG_UN  +---+
                //   |    |   |
                //   |    +- -+
                //   |    |   |
                //   v    +---+

                const uint Nd4_K_USGN_USGK = Nd4 * K * UNROLL_SG_N * UNROLL_SG_K;
                const uint Nd4_K_USGN_USGK_d_subgroupsize = (Nd4_K_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                [[unroll]] for (uint q = 0; q < Nd4_K_USGN_USGK_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                    if (Nd4_K_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Nd4_K_USGN_USGK)
                    {
                        const uint zk = siq / (Nd4 * K * UNROLL_SG_N);
                        const uint znij = siq % (Nd4 * K * UNROLL_SG_N);
                        const uint zn = znij / (Nd4 * K);
                        const uint ij = znij % (Nd4 * K);

                        uvec2 v = uvec2(0);

                        {
                            const uint i = ij / Nd4;
                            const uint j = ij % Nd4;

                            const uint gk = ki + zk * K + i;
                            const uint gn = (ni + zn) * Nd4 + j;

                            if (gk < psc(GK))
                            {
                                const uvec4 gn4 = gn * 4 + uvec4(0, 1, 2, 3);

                                if (p.B_hstep % 4 == 0)
                                {
                                    const uint bi = gk * (p.B_hstep / 4) + gn;

                                    v = B_blob_data[bi];

                                    uvec4 mask4 = uvec4(lessThan(gn4, uvec4(psc(GN)))) * 0xFFFFu;
                                    uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                    v = v & packed_mask;
                                }
                                else
                                {
                                    vec2 v4a = vec2(0.f);
                                    vec2 v4b = vec2(0.f);

                                    const uvec4 bi4 = gk * p.B_hstep + gn4;
                                    const uvec4 bi4d4 = bi4 / 4;
                                    const uvec4 bi4m4d2 = (bi4 % 4) / 2;
                                    const uvec4 bi4m2 = bi4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                    if (gn4.r < psc(GN)) v4a.r = unpackBFloat2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                    if (gn4.g < psc(GN)) v4a.g = unpackBFloat2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                    if (gn4.b < psc(GN)) v4b.r = unpackBFloat2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                    if (gn4.a < psc(GN)) v4b.g = unpackBFloat2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                    v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                    if (gn4.r < psc(GN)) v4a.r = unpackHalf2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                    if (gn4.g < psc(GN)) v4a.g = unpackHalf2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                    if (gn4.b < psc(GN)) v4b.r = unpackHalf2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                    if (gn4.a < psc(GN)) v4b.g = unpackHalf2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                    v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                }
                            }

                            tmp_b[(((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * K + i) * Nd4p + j] = v;
                        }
                    }
                }
            }
            else // if (psc(B_elempack) == 4)
            {
                const uint Kd4_N_USGN_USGK = Kd4 * N * UNROLL_SG_N * UNROLL_SG_K;
                const uint Kd4_N_USGN_USGK_d_subgroupsize = (Kd4_N_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                [[unroll]] for (uint q = 0; q < Kd4_N_USGN_USGK_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                    if (Kd4_N_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Kd4_N_USGN_USGK)
                    {
                        const uint zk = siq / (Kd4 * N * UNROLL_SG_N);
                        const uint znij = siq % (Kd4 * N * UNROLL_SG_N);
                        const uint zn = znij / (Kd4 * N);
                        const uint ij = znij % (Kd4 * N);
                        const uint i = ij / Kd4;
                        const uint j = ij % Kd4;

                        uvec2 v = uvec2(0);

                        const uint gn = (ni + zn) * N + i;
                        const uint gk = ki / 4 + zk * Kd4 + j;

                        if (gn < psc(GN))
                        {
                            v = B_blob_data[gk * p.B_hstep + gn];
                        }

                        tmp_b[(((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * N + i) * Kd4p + j] = v;
                    }
                }
            }
        }
        else
        {
            if (psc(B_elempack) == 1)
            {
                //        +-K-+
                //        N   |
                //        +SG_UN
                //        |   |
                //     ^  +---+
                //     |  |   |
                //   SG_UK+- -+
                //     |  |   |
                //   ^ v  +---+
                //   |    |   |
                //   |    +- -+
                //   |    |   |
                // WG_UN  +---+
                //   |    |   |
                //   |    +- -+
                //   |    |   |
                //   v    +---+

                const uint Kd4_N_USGN_USGK = Kd4 * N * UNROLL_SG_N * UNROLL_SG_K;
                const uint Kd4_N_USGN_USGK_d_subgroupsize = (Kd4_N_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                [[unroll]] for (uint q = 0; q < Kd4_N_USGN_USGK_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                    if (Kd4_N_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Kd4_N_USGN_USGK)
                    {
                        const uint zk = siq / (Kd4 * N * UNROLL_SG_N);
                        const uint znij = siq % (Kd4 * N * UNROLL_SG_N);
                        const uint zn = znij / (Kd4 * N);
                        const uint ij = znij % (Kd4 * N);

                        uvec2 v = uvec2(0);

                        {
                            const uint j = ij / Kd4;
                            const uint i = ij % Kd4;

                            const uint gk = ki / 4 + zk * Kd4 + i;
                            const uint gn = (ni + zn) * N + j;

                            if (gn < psc(GN))
                            {
                                const uvec4 gk4 = gk * 4 + uvec4(0, 1, 2, 3);

                                if (p.B_hstep % 4 == 0)
                                {
                                    const uint bi = gn * (p.B_hstep / 4) + gk;

                                    v = B_blob_data[bi];

                                    uvec4 mask4 = uvec4(lessThan(gk4, uvec4(psc(GK)))) * 0xFFFFu;
                                    uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                    v = v & packed_mask;
                                }
                                else
                                {
                                    vec2 v4a = vec2(0.f);
                                    vec2 v4b = vec2(0.f);

                                    const uvec4 bi4 = gn * p.B_hstep + gk4;
                                    const uvec4 bi4d4 = bi4 / 4;
                                    const uvec4 bi4m4d2 = (bi4 % 4) / 2;
                                    const uvec4 bi4m2 = bi4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                    if (gk4.r < psc(GK)) v4a.r = unpackBFloat2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                    if (gk4.g < psc(GK)) v4a.g = unpackBFloat2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                    if (gk4.b < psc(GK)) v4b.r = unpackBFloat2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                    if (gk4.a < psc(GK)) v4b.g = unpackBFloat2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                    v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                    if (gk4.r < psc(GK)) v4a.r = unpackHalf2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                    if (gk4.g < psc(GK)) v4a.g = unpackHalf2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                    if (gk4.b < psc(GK)) v4b.r = unpackHalf2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                    if (gk4.a < psc(GK)) v4b.g = unpackHalf2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                    v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                }
                            }

                            tmp_b[(((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * N + j) * Kd4p + i] = v;
                        }
                    }
                }
            }
            else // if (psc(B_elempack) == 4)
            {
                const uint Nd4_K_USGN_USGK = Nd4 * K * UNROLL_SG_N * UNROLL_SG_K;
                const uint Nd4_K_USGN_USGK_d_subgroupsize = (Nd4_K_USGN_USGK + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                [[unroll]] for (uint q = 0; q < Nd4_K_USGN_USGK_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                    if (Nd4_K_USGN_USGK % (subgroup_size * UNROLL_WG_M) == 0 || siq < Nd4_K_USGN_USGK)
                    {
                        const uint zk = siq / (Nd4 * K * UNROLL_SG_N);
                        const uint znij = siq % (Nd4 * K * UNROLL_SG_N);
                        const uint zn = znij / (Nd4 * K);
                        const uint ij = znij % (Nd4 * K);
                        const uint j = ij / Nd4;
                        const uint i = ij % Nd4;

                        uvec2 v = uvec2(0);

                        const uint gk = ki + zk * K + j;
                        const uint gn = (ni + zn) * Nd4 + i;

                        if (gk < psc(GK))
                        {
                            v = B_blob_data[gn * p.B_hstep + gk];
                        }

                        tmp_b[(((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * K + j) * Nd4p + i] = v;
                    }
                }
            }
        }

        barrier();

#if ncnn_VK_KHR_cooperative_matrix
#if NCNN_bf16_storage || NCNN_bf16_packed
        coopmat<bfloat16_t, gl_ScopeSubgroup, M, K, gl_MatrixUseA> A[UNROLL_SG_M];
        coopmat<bfloat16_t, gl_ScopeSubgroup, K, N, gl_MatrixUseB> B[UNROLL_SG_N];
#else
        coopmat<float16_t, gl_ScopeSubgroup, M, K, gl_MatrixUseA> A[UNROLL_SG_M];
        coopmat<float16_t, gl_ScopeSubgroup, K, N, gl_MatrixUseB> B[UNROLL_SG_N];
#endif
#elif ncnn_VK_NV_cooperative_matrix
        fcoopmatNV<16, gl_ScopeSubgroup, M, K> A[UNROLL_SG_M];
        fcoopmatNV<16, gl_ScopeSubgroup, K, N> B[UNROLL_SG_N];
#endif

        [[unroll]] for (uint zk = 0; zk < UNROLL_SG_K; zk++)
        {
            [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
            {
                if (transA == 0)
                {
                    if (psc(A_elempack) == 4)
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Md4p * K), Md4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Md4p * K), Md4p, true);
#endif
                    }
                    else
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, false);
#endif
                    }
                }
                else
                {
                    if (psc(A_elempack) == 4)
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, false);
#endif
                    }
                    else
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Md4p * K), Md4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(A[zm], tmp_a, ((sgmi * UNROLL_SG_K + zk) * UNROLL_SG_M + zm) * (Md4p * K), Md4p, true);
#endif
                    }
                }
            }

            [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
            {
                if (transB == 0)
                {
                    if (psc(B_elempack) == 4)
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, true);
#endif
                    }
                    else
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, false);
#endif
                    }
                }
                else
                {
                    if (psc(B_elempack) == 4)
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, false);
#endif
                    }
                    else
                    {
#if ncnn_VK_KHR_cooperative_matrix
                        coopMatLoad(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                        coopMatLoadNV(B[zn], tmp_b, ((sgni * UNROLL_SG_K + zk) * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, true);
#endif
                    }
                }
            }

            // sum += k * v
            [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
            {
                [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
                {
#if ncnn_VK_KHR_cooperative_matrix
                    sum[zn][zm] = coopMatMulAdd(A[zm], B[zn], sum[zn][zm]);
#elif ncnn_VK_NV_cooperative_matrix
                    sum[zn][zm] = coopMatMulAddNV(A[zm], B[zn], sum[zn][zm]);
#endif
                }
            }
        }

        k += UNROLL_SG_K;
    }

    for (; k < kk; k++)
    {
        const uint ki = k * K;

        barrier();

        // load A
        if (transA == 0)
        {
            if (psc(A_elempack) == 1)
            {
                //      +-K-+
                //      M   |
                //      +SG_UM
                //      |   |
                //   ^  +---+
                //   |  |   |
                // WG_UM+- -+
                //   |  |   |
                //   v  +---+

                const uint Kd4_M_USGM = Kd4 * M * UNROLL_SG_M;
                const uint Kd4_M_USGM_d_subgroupsize = (Kd4_M_USGM + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                [[unroll]] for (uint q = 0; q < Kd4_M_USGM_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                    if (Kd4_M_USGM % (subgroup_size * UNROLL_WG_N) == 0 || siq < Kd4_M_USGM)
                    {
                        const uint zm = siq / (Kd4 * M);
                        const uint ij = siq % (Kd4 * M);

                        uvec2 v = uvec2(0);

                        {
                            const uint j = ij / Kd4;
                            const uint i = ij % Kd4;

                            const uint gk = ki / 4 + i;
                            const uint gm = (mi + zm) * M + j;

                            if (gm < psc(GM))
                            {
                                const uvec4 gk4 = gk * 4 + uvec4(0, 1, 2, 3);

                                if (p.A_hstep % 4 == 0)
                                {
                                    const uint ai = gm * (p.A_hstep / 4) + gk;

                                    v = A_blob_data[ai];

                                    uvec4 mask4 = uvec4(lessThan(gk4, uvec4(psc(GK)))) * 0xFFFFu;
                                    uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                    v = v & packed_mask;
                                }
                                else
                                {
                                    vec2 v4a = vec2(0.f);
                                    vec2 v4b = vec2(0.f);

                                    const uvec4 ai4 = gm * p.A_hstep + gk4;
                                    const uvec4 ai4d4 = ai4 / 4;
                                    const uvec4 ai4m4d2 = (ai4 % 4) / 2;
                                    const uvec4 ai4m2 = ai4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                    if (gk4.r < psc(GK)) v4a.r = unpackBFloat2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                    if (gk4.g < psc(GK)) v4a.g = unpackBFloat2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                    if (gk4.b < psc(GK)) v4b.r = unpackBFloat2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                    if (gk4.a < psc(GK)) v4b.g = unpackBFloat2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                    v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                    if (gk4.r < psc(GK)) v4a.r = unpackHalf2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                    if (gk4.g < psc(GK)) v4a.g = unpackHalf2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                    if (gk4.b < psc(GK)) v4b.r = unpackHalf2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                    if (gk4.a < psc(GK)) v4b.g = unpackHalf2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                    v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                }
                            }

                            tmp_a[((sgmi * UNROLL_SG_M + zm) * M + j) * Kd4p + i] = v;
                        }
                    }
                }
            }
            else // if (psc(A_elempack) == 4)
            {
                const uint Md4_K_USGM = Md4 * K * UNROLL_SG_M;
                const uint Md4_K_USGM_d_subgroupsize = (Md4_K_USGM + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                [[unroll]] for (uint q = 0; q < Md4_K_USGM_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                    if (Md4_K_USGM % (subgroup_size * UNROLL_WG_N) == 0 || siq < Md4_K_USGM)
                    {
                        const uint zm = siq / (Md4 * K);
                        const uint ij = siq % (Md4 * K);
                        const uint i = ij / Md4;
                        const uint j = ij % Md4;

                        uvec2 v = uvec2(0);

                        const uint gk = ki + i;
                        const uint gm = (mi + zm) * Md4 + j;

                        if (gk < psc(GK))
                        {
                            v = A_blob_data[gm * p.A_hstep + gk];
                        }

                        tmp_a[((sgmi * UNROLL_SG_M + zm) * K + i) * Md4p + j] = v;
                    }
                }
            }
        }
        else
        {
            if (psc(A_elempack) == 1)
            {
                //      +-M-+
                //      K   |
                //      +SG_UM
                //      |   |
                //   ^  +---+
                //   |  |   |
                // WG_UM+- -+
                //   |  |   |
                //   v  +---+

                const uint Md4_K_USGM = Md4 * K * UNROLL_SG_M;
                const uint Md4_K_USGM_d_subgroupsize = (Md4_K_USGM + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                [[unroll]] for (uint q = 0; q < Md4_K_USGM_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                    if (Md4_K_USGM % (subgroup_size * UNROLL_WG_N) == 0 || siq < Md4_K_USGM)
                    {
                        const uint zm = siq / (Md4 * K);
                        const uint ij = siq % (Md4 * K);

                        uvec2 v = uvec2(0);

                        {
                            const uint i = ij / Md4;
                            const uint j = ij % Md4;

                            const uint gk = ki + i;
                            const uint gm = (mi + zm) * Md4 + j;

                            if (gk < psc(GK))
                            {
                                if (p.A_hstep % 4 == 0)
                                {
                                    const uint ai = gk * (p.A_hstep / 4) + gm;

                                    v = A_blob_data[ai];

                                    uvec4 gm4_vals = gm * 4 + uvec4(0, 1, 2, 3);
                                    uvec4 mask4 = uvec4(lessThan(gm4_vals, uvec4(psc(GM)))) * 0xFFFFu;
                                    uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                    v = v & packed_mask;
                                }
                                else
                                {
                                    const uvec4 gm4 = gm * 4 + uvec4(0, 1, 2, 3);

                                    vec2 v4a = vec2(0.f);
                                    vec2 v4b = vec2(0.f);

                                    const uvec4 ai4 = gk * p.A_hstep + gm4;
                                    const uvec4 ai4d4 = ai4 / 4;
                                    const uvec4 ai4m4d2 = (ai4 % 4) / 2;
                                    const uvec4 ai4m2 = ai4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                    if (gm4.r < psc(GM)) v4a.r = unpackBFloat2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                    if (gm4.g < psc(GM)) v4a.g = unpackBFloat2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                    if (gm4.b < psc(GM)) v4b.r = unpackBFloat2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                    if (gm4.a < psc(GM)) v4b.g = unpackBFloat2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                    v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                    if (gm4.r < psc(GM)) v4a.r = unpackHalf2x16(A_blob_data[ai4d4.r][ai4m4d2.r])[ai4m2.r];
                                    if (gm4.g < psc(GM)) v4a.g = unpackHalf2x16(A_blob_data[ai4d4.g][ai4m4d2.g])[ai4m2.g];
                                    if (gm4.b < psc(GM)) v4b.r = unpackHalf2x16(A_blob_data[ai4d4.b][ai4m4d2.b])[ai4m2.b];
                                    if (gm4.a < psc(GM)) v4b.g = unpackHalf2x16(A_blob_data[ai4d4.a][ai4m4d2.a])[ai4m2.a];

                                    v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                }
                            }

                            tmp_a[((sgmi * UNROLL_SG_M + zm) * K + i) * Md4p + j] = v;
                        }
                    }
                }
            }
            else // if (psc(A_elempack) == 4)
            {
                const uint Kd4_M_USGM = Kd4 * M * UNROLL_SG_M;
                const uint Kd4_M_USGM_d_subgroupsize = (Kd4_M_USGM + (subgroup_size * UNROLL_WG_N - 1)) / (subgroup_size * UNROLL_WG_N);
                [[unroll]] for (uint q = 0; q < Kd4_M_USGM_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_N + sgni) * subgroup_size + si;

                    if (Kd4_M_USGM % (subgroup_size * UNROLL_WG_N) == 0 || siq < Kd4_M_USGM)
                    {
                        const uint zm = siq / (Kd4 * M);
                        const uint ij = siq % (Kd4 * M);
                        const uint j = ij / Kd4;
                        const uint i = ij % Kd4;

                        uvec2 v = uvec2(0);

                        const uint gk = ki / 4 + i;
                        const uint gm = (mi + zm) * M + j;

                        if (gm < psc(GM))
                        {
                            v = A_blob_data[gk * p.A_hstep + gm];

                            uvec4 gk4 = gk * 4 + uvec4(0, 1, 2, 3);
                            uvec4 mask4 = uvec4(lessThan(gk4, uvec4(psc(GK)))) * 0xFFFFu;
                            uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                            v = v & packed_mask;
                        }

                        tmp_a[((sgmi * UNROLL_SG_M + zm) * M + j) * Kd4p + i] = v;
                    }
                }
            }
        }

        // load B
        if (transB == 0)
        {
            if (psc(B_elempack) == 1)
            {
                //      +-N-+
                //      K   |
                //      +SG_UN
                //      |   |
                //   ^  +---+
                //   |  |   |
                // WG_UN+- -+
                //   |  |   |
                //   v  +---+

                const uint Nd4_K_USGN = Nd4 * K * UNROLL_SG_N;
                const uint Nd4_K_USGN_d_subgroupsize = (Nd4_K_USGN + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                [[unroll]] for (uint q = 0; q < Nd4_K_USGN_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                    if (Nd4_K_USGN % (subgroup_size * UNROLL_WG_M) == 0 || siq < Nd4_K_USGN)
                    {
                        const uint zn = siq / (Nd4 * K);
                        const uint ij = siq % (Nd4 * K);

                        uvec2 v = uvec2(0);

                        {
                            const uint i = ij / Nd4;
                            const uint j = ij % Nd4;

                            const uint gk = ki + i;
                            const uint gn = (ni + zn) * Nd4 + j;

                            if (gk < psc(GK))
                            {
                                const uvec4 gn4 = gn * 4 + uvec4(0, 1, 2, 3);

                                if (p.B_hstep % 4 == 0)
                                {
                                    const uint bi = gk * (p.B_hstep / 4) + gn;

                                    v = B_blob_data[bi];

                                    uvec4 mask4 = uvec4(lessThan(gn4, uvec4(psc(GN)))) * 0xFFFFu;
                                    uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                    v = v & packed_mask;
                                }
                                else
                                {
                                    vec2 v4a = vec2(0.f);
                                    vec2 v4b = vec2(0.f);

                                    const uvec4 bi4 = gk * p.B_hstep + gn4;
                                    const uvec4 bi4d4 = bi4 / 4;
                                    const uvec4 bi4m4d2 = (bi4 % 4) / 2;
                                    const uvec4 bi4m2 = bi4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                    if (gn4.r < psc(GN)) v4a.r = unpackBFloat2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                    if (gn4.g < psc(GN)) v4a.g = unpackBFloat2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                    if (gn4.b < psc(GN)) v4b.r = unpackBFloat2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                    if (gn4.a < psc(GN)) v4b.g = unpackBFloat2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                    v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                    if (gn4.r < psc(GN)) v4a.r = unpackHalf2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                    if (gn4.g < psc(GN)) v4a.g = unpackHalf2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                    if (gn4.b < psc(GN)) v4b.r = unpackHalf2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                    if (gn4.a < psc(GN)) v4b.g = unpackHalf2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                    v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                }
                            }

                            tmp_b[((sgni * UNROLL_SG_N + zn) * K + i) * Nd4p + j] = v;
                        }
                    }
                }
            }
            else // if (psc(B_elempack) == 4)
            {
                const uint Kd4_N_USGN = Kd4 * N * UNROLL_SG_N;
                const uint Kd4_N_USGN_d_subgroupsize = (Kd4_N_USGN + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                [[unroll]] for (uint q = 0; q < Kd4_N_USGN_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                    if (Kd4_N_USGN % (subgroup_size * UNROLL_WG_M) == 0 || siq < Kd4_N_USGN)
                    {
                        const uint zn = siq / (Kd4 * N);
                        const uint ij = siq % (Kd4 * N);
                        const uint i = ij / Kd4;
                        const uint j = ij % Kd4;

                        uvec2 v = uvec2(0);

                        const uint gn = (ni + zn) * N + i;
                        const uint gk = ki / 4 + j;

                        if (gn < psc(GN))
                        {
                            v = B_blob_data[gk * p.B_hstep + gn];
                        }

                        tmp_b[((sgni * UNROLL_SG_N + zn) * N + i) * Kd4p + j] = v;
                    }
                }
            }
        }
        else
        {
            if (psc(B_elempack) == 1)
            {
                //      +-K-+
                //      N   |
                //      +SG_UN
                //      |   |
                //   ^  +---+
                //   |  |   |
                // WG_UN+- -+
                //   |  |   |
                //   v  +---+

                const uint Kd4_N_USGN = Kd4 * N * UNROLL_SG_N;
                const uint Kd4_N_USGN_d_subgroupsize = (Kd4_N_USGN + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                [[unroll]] for (uint q = 0; q < Kd4_N_USGN_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                    if (Kd4_N_USGN % (subgroup_size * UNROLL_WG_M) == 0 || siq < Kd4_N_USGN)
                    {
                        const uint zn = siq / (Kd4 * N);
                        const uint ij = siq % (Kd4 * N);

                        uvec2 v = uvec2(0);

                        {
                            const uint j = ij / Kd4;
                            const uint i = ij % Kd4;

                            const uint gk = ki / 4 + i;
                            const uint gn = (ni + zn) * N + j;

                            if (gn < psc(GN))
                            {
                                const uvec4 gk4 = gk * 4 + uvec4(0, 1, 2, 3);

                                if (p.B_hstep % 4 == 0)
                                {
                                    const uint bi = gn * (p.B_hstep / 4) + gk;

                                    v = B_blob_data[bi];

                                    uvec4 mask4 = uvec4(lessThan(gk4, uvec4(psc(GK)))) * 0xFFFFu;
                                    uvec2 packed_mask = uvec2(mask4.x | (mask4.y << 16), mask4.z | (mask4.w << 16));

                                    v = v & packed_mask;
                                }
                                else
                                {
                                    vec2 v4a = vec2(0.f);
                                    vec2 v4b = vec2(0.f);

                                    const uvec4 bi4 = gn * p.B_hstep + gk4;
                                    const uvec4 bi4d4 = bi4 / 4;
                                    const uvec4 bi4m4d2 = (bi4 % 4) / 2;
                                    const uvec4 bi4m2 = bi4 % 2;

#if NCNN_bf16_storage || NCNN_bf16_packed
                                    if (gk4.r < psc(GK)) v4a.r = unpackBFloat2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                    if (gk4.g < psc(GK)) v4a.g = unpackBFloat2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                    if (gk4.b < psc(GK)) v4b.r = unpackBFloat2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                    if (gk4.a < psc(GK)) v4b.g = unpackBFloat2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                    v = uvec2(packBFloat2x16(v4a), packBFloat2x16(v4b));
#else
                                    if (gk4.r < psc(GK)) v4a.r = unpackHalf2x16(B_blob_data[bi4d4.r][bi4m4d2.r])[bi4m2.r];
                                    if (gk4.g < psc(GK)) v4a.g = unpackHalf2x16(B_blob_data[bi4d4.g][bi4m4d2.g])[bi4m2.g];
                                    if (gk4.b < psc(GK)) v4b.r = unpackHalf2x16(B_blob_data[bi4d4.b][bi4m4d2.b])[bi4m2.b];
                                    if (gk4.a < psc(GK)) v4b.g = unpackHalf2x16(B_blob_data[bi4d4.a][bi4m4d2.a])[bi4m2.a];

                                    v = uvec2(packHalf2x16(v4a), packHalf2x16(v4b));
#endif
                                }
                            }

                            tmp_b[((sgni * UNROLL_SG_N + zn) * N + j) * Kd4p + i] = v;
                        }
                    }
                }
            }
            else // if (psc(B_elempack) == 4)
            {
                const uint Nd4_K_USGN = Nd4 * K * UNROLL_SG_N;
                const uint Nd4_K_USGN_d_subgroupsize = (Nd4_K_USGN + (subgroup_size * UNROLL_WG_M - 1)) / (subgroup_size * UNROLL_WG_M);
                [[unroll]] for (uint q = 0; q < Nd4_K_USGN_d_subgroupsize; q++)
                {
                    const uint siq = (q * UNROLL_WG_M + sgmi) * subgroup_size + si;

                    if (Nd4_K_USGN % (subgroup_size * UNROLL_WG_M) == 0 || siq < Nd4_K_USGN)
                    {
                        const uint zn = siq / (Nd4 * K);
                        const uint ij = siq % (Nd4 * K);
                        const uint j = ij / Nd4;
                        const uint i = ij % Nd4;

                        uvec2 v = uvec2(0);

                        const uint gk = ki + j;
                        const uint gn = (ni + zn) * Nd4 + i;

                        if (gk < psc(GK))
                        {
                            v = B_blob_data[gn * p.B_hstep + gk];
                        }

                        tmp_b[((sgni * UNROLL_SG_N + zn) * K + j) * Nd4p + i] = v;
                    }
                }
            }
        }

        barrier();

#if ncnn_VK_KHR_cooperative_matrix
#if NCNN_bf16_storage || NCNN_bf16_packed
        coopmat<bfloat16_t, gl_ScopeSubgroup, M, K, gl_MatrixUseA> A[UNROLL_SG_M];
        coopmat<bfloat16_t, gl_ScopeSubgroup, K, N, gl_MatrixUseB> B[UNROLL_SG_N];
#else
        coopmat<float16_t, gl_ScopeSubgroup, M, K, gl_MatrixUseA> A[UNROLL_SG_M];
        coopmat<float16_t, gl_ScopeSubgroup, K, N, gl_MatrixUseB> B[UNROLL_SG_N];
#endif
#elif ncnn_VK_NV_cooperative_matrix
        fcoopmatNV<16, gl_ScopeSubgroup, M, K> A[UNROLL_SG_M];
        fcoopmatNV<16, gl_ScopeSubgroup, K, N> B[UNROLL_SG_N];
#endif

        [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
        {
            if (transA == 0)
            {
                if (psc(A_elempack) == 4)
                {
#if ncnn_VK_KHR_cooperative_matrix
                    coopMatLoad(A[zm], tmp_a, (sgmi * UNROLL_SG_M + zm) * (Md4p * K), Md4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                    coopMatLoadNV(A[zm], tmp_a, (sgmi * UNROLL_SG_M + zm) * (Md4p * K), Md4p, true);
#endif
                }
                else
                {
#if ncnn_VK_KHR_cooperative_matrix
                    coopMatLoad(A[zm], tmp_a, (sgmi * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                    coopMatLoadNV(A[zm], tmp_a, (sgmi * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, false);
#endif
                }
            }
            else
            {
                if (psc(A_elempack) == 4)
                {
#if ncnn_VK_KHR_cooperative_matrix
                    coopMatLoad(A[zm], tmp_a, (sgmi * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                    coopMatLoadNV(A[zm], tmp_a, (sgmi * UNROLL_SG_M + zm) * (Kd4p * M), Kd4p, false);
#endif
                }
                else
                {
#if ncnn_VK_KHR_cooperative_matrix
                    coopMatLoad(A[zm], tmp_a, (sgmi * UNROLL_SG_M + zm) * (Md4p * K), Md4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                    coopMatLoadNV(A[zm], tmp_a, (sgmi * UNROLL_SG_M + zm) * (Md4p * K), Md4p, true);
#endif
                }
            }
        }

        [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
        {
            if (transB == 0)
            {
                if (psc(B_elempack) == 4)
                {
#if ncnn_VK_KHR_cooperative_matrix
                    coopMatLoad(B[zn], tmp_b, (sgni * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                    coopMatLoadNV(B[zn], tmp_b, (sgni * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, true);
#endif
                }
                else
                {
#if ncnn_VK_KHR_cooperative_matrix
                    coopMatLoad(B[zn], tmp_b, (sgni * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                    coopMatLoadNV(B[zn], tmp_b, (sgni * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, false);
#endif
                }
            }
            else
            {
                if (psc(B_elempack) == 4)
                {
#if ncnn_VK_KHR_cooperative_matrix
                    coopMatLoad(B[zn], tmp_b, (sgni * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#elif ncnn_VK_NV_cooperative_matrix
                    coopMatLoadNV(B[zn], tmp_b, (sgni * UNROLL_SG_N + zn) * (Nd4p * K), Nd4p, false);
#endif
                }
                else
                {
#if ncnn_VK_KHR_cooperative_matrix
                    coopMatLoad(B[zn], tmp_b, (sgni * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, gl_CooperativeMatrixLayoutColumnMajor);
#elif ncnn_VK_NV_cooperative_matrix
                    coopMatLoadNV(B[zn], tmp_b, (sgni * UNROLL_SG_N + zn) * (Kd4p * N), Kd4p, true);
#endif
                }
            }
        }

        // sum += k * v
        [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
        {
            [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
            {
#if ncnn_VK_KHR_cooperative_matrix
                sum[zn][zm] = coopMatMulAdd(A[zm], B[zn], sum[zn][zm]);
#elif ncnn_VK_NV_cooperative_matrix
                sum[zn][zm] = coopMatMulAddNV(A[zm], B[zn], sum[zn][zm]);
#endif
            }
        }
    }

    if (alpha != 1.f)
    {
        [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
        {
            [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
            {
                sum[zn][zm] = sum[zn][zm] * afp(alpha);
            }
        }
    }

    [[unroll]] for (uint zn = 0; zn < UNROLL_SG_N; zn++)
    {
        [[unroll]] for (uint zm = 0; zm < UNROLL_SG_M; zm++)
        {
            if (output_transpose == 0)
            {
                if (psc(out_elempack) == 4)
                {
                    // out_elempack=4: ColumnMajor, stride Md4 (NO PAD)
#if ncnn_VK_KHR_cooperative_matrix
#if NCNN_fp16_arithmetic
                    coopMatStore(sum[zn][zm], tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Md4p * N), Md4p, gl_CooperativeMatrixLayoutColumnMajor);
#else
#if NCNN_bf16_storage || NCNN_bf16_packed
                    coopmat<bfloat16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> sum_fp16 = coopmat<bfloat16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(sum[zn][zm]);
#else
                    coopmat<float16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> sum_fp16 = coopmat<float16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(sum[zn][zm]);
#endif
                    coopMatStore(sum_fp16, tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Md4p * N), Md4p, gl_CooperativeMatrixLayoutColumnMajor);
#endif
#elif ncnn_VK_NV_cooperative_matrix
#if NCNN_fp16_arithmetic
                    coopMatStoreNV(sum[zn][zm], tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Md4p * N), Md4p, true);
#else
                    fcoopmatNV<16, gl_ScopeSubgroup, M, N> sum_fp16 = fcoopmatNV<16, gl_ScopeSubgroup, M, N>(sum[zn][zm]);
                    coopMatStoreNV(sum_fp16, tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Md4p * N), Md4p, true);
#endif
#endif
                }
                else
                {
                    // out_elempack=1: RowMajor, stride Nd4p
#if ncnn_VK_KHR_cooperative_matrix
#if NCNN_fp16_arithmetic
                    coopMatStore(sum[zn][zm], tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Nd4p * M), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#else
#if NCNN_bf16_storage || NCNN_bf16_packed
                    coopmat<bfloat16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> sum_fp16 = coopmat<bfloat16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(sum[zn][zm]);
#else
                    coopmat<float16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> sum_fp16 = coopmat<float16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(sum[zn][zm]);
#endif
                    coopMatStore(sum_fp16, tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Nd4p * M), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#endif
#elif ncnn_VK_NV_cooperative_matrix
#if NCNN_fp16_arithmetic
                    coopMatStoreNV(sum[zn][zm], tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Nd4p * M), Nd4p, false);
#else
                    fcoopmatNV<16, gl_ScopeSubgroup, M, N> sum_fp16 = fcoopmatNV<16, gl_ScopeSubgroup, M, N>(sum[zn][zm]);
                    coopMatStoreNV(sum_fp16, tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Nd4p * M), Nd4p, false);
#endif
#endif
                }
            }
            else
            {
                if (psc(out_elempack) == 4)
                {
#if ncnn_VK_KHR_cooperative_matrix
#if NCNN_fp16_arithmetic
                    coopMatStore(sum[zn][zm], tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Nd4p * M), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#else
#if NCNN_bf16_storage || NCNN_bf16_packed
                    coopmat<bfloat16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> sum_fp16 = coopmat<bfloat16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(sum[zn][zm]);
#else
                    coopmat<float16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> sum_fp16 = coopmat<float16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(sum[zn][zm]);
#endif
                    coopMatStore(sum_fp16, tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Nd4p * M), Nd4p, gl_CooperativeMatrixLayoutRowMajor);
#endif
#elif ncnn_VK_NV_cooperative_matrix
#if NCNN_fp16_arithmetic
                    coopMatStoreNV(sum[zn][zm], tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Nd4p * M), Nd4p, false);
#else
                    fcoopmatNV<16, gl_ScopeSubgroup, M, N> sum_fp16 = fcoopmatNV<16, gl_ScopeSubgroup, M, N>(sum[zn][zm]);
                    coopMatStoreNV(sum_fp16, tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Nd4p * M), Nd4p, false);
#endif
#endif
                }
                else
                {
#if ncnn_VK_KHR_cooperative_matrix
#if NCNN_fp16_arithmetic
                    coopMatStore(sum[zn][zm], tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Md4p * N), Md4p, gl_CooperativeMatrixLayoutColumnMajor);
#else
#if NCNN_bf16_storage || NCNN_bf16_packed
                    coopmat<bfloat16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> sum_fp16 = coopmat<bfloat16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(sum[zn][zm]);
#else
                    coopmat<float16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator> sum_fp16 = coopmat<float16_t, gl_ScopeSubgroup, M, N, gl_MatrixUseAccumulator>(sum[zn][zm]);
#endif
                    coopMatStore(sum_fp16, tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Md4p * N), Md4p, gl_CooperativeMatrixLayoutColumnMajor);
#endif
#elif ncnn_VK_NV_cooperative_matrix
#if NCNN_fp16_arithmetic
                    coopMatStoreNV(sum[zn][zm], tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Md4p * N), Md4p, true);
#else
                    fcoopmatNV<16, gl_ScopeSubgroup, M, N> sum_fp16 = fcoopmatNV<16, gl_ScopeSubgroup, M, N>(sum[zn][zm]);
                    coopMatStoreNV(sum_fp16, tmp_o, ((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * (Md4p * N), Md4p, true);
#endif
#endif
                }
            }
        }
    }

    barrier();

    // store top_blob
    if (output_transpose == 0)
    {
        //          +-N-+
        //          M   |
        //          +SG_UM
        //          |   |
        //       ^  +---+
        //       |  |   |
        //     SG_UN+- -+
        //       |  |   |
        //     ^ v  +---+
        //     |    |   |
        //     |    +- -+
        //     |    |   |
        //   WG_UM  +- -+
        //     |    |   |
        //     |    +- -+
        //     |    |   |
        //   ^ v    +---+
        //   |      |   |
        //   |      +- -+
        //   |      |   |
        //   |      +---+
        //   |      |   |
        //   |      +- -+
        //   |      |   |
        // WG_UN    +---+
        //   |      |   |
        //   |      +- -+
        //   |      |   |
        //   |      +---+
        //   |      |   |
        //   |      +- -+
        //   |      |   |
        //   v      +---+

        if (psc(out_elempack) == 4)
        {
            // ColumnMajor (no PAD): tmp_o[base + n * Md4 + m4], each uvec2 = sfpvec4 of 4 consecutive M values
            const uint Md4_N_USGM_USGN = Md4 * N * UNROLL_SG_M * UNROLL_SG_N;
            const uint Md4_N_USGM_USGN_d_subgroupsize = (Md4_N_USGM_USGN + subgroup_size - 1) / subgroup_size;
            [[unroll]] for (uint q = 0; q < Md4_N_USGM_USGN_d_subgroupsize; q++)
            {
                const uint siq = si + q * subgroup_size;

                if (Md4_N_USGM_USGN % subgroup_size == 0 || siq < Md4_N_USGM_USGN)
                {
                    const uint zn = siq / (Md4 * N * UNROLL_SG_M);
                    const uint zmij = siq % (Md4 * N * UNROLL_SG_M);
                    const uint zm = zmij / (Md4 * N);
                    const uint ij = zmij % (Md4 * N);
                    const uint i = ij / Md4;
                    const uint j = ij % Md4;

                    const uint gn = (ni + zn) * N + i;
                    const uint gm = (mi + zm) * Md4 + j;

                    if (gm * 4 < psc(GM) && gn < psc(GN))
                    {
                        uvec2 v = tmp_o[(((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * N + i) * Md4p + j];

                        const uint gi = gm * p.outhstep + gn;

                        top_blob_data_4[gi] = v;
                    }
                }
            }
        }
        else
        {
            const uint Nd4_M_USGM_USGN = Nd4 * M * UNROLL_SG_M * UNROLL_SG_N;
            const uint Nd4_M_USGM_USGN_d_subgroupsize = (Nd4_M_USGM_USGN + subgroup_size - 1) / subgroup_size;
            [[unroll]] for (uint q = 0; q < Nd4_M_USGM_USGN_d_subgroupsize; q++)
            {
                const uint siq = si + q * subgroup_size;

                if (Nd4_M_USGM_USGN % subgroup_size == 0 || siq < Nd4_M_USGM_USGN)
                {
                    const uint zn = siq / (Nd4 * M * UNROLL_SG_M);
                    const uint zmij = siq % (Nd4 * M * UNROLL_SG_M);
                    const uint zm = zmij / (Nd4 * M);
                    const uint ij = zmij % (Nd4 * M);
                    const uint i = ij / Nd4;
                    const uint j = ij % Nd4;

                    const uint gm = (mi + zm) * M + i;
                    const uint gn = (ni + zn) * Nd4 + j;

                    if (gm < psc(GM))
                    {
                        uvec2 v = tmp_o[(((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * M + i) * Nd4p + j];

#if NCNN_bf16_storage || NCNN_bf16_packed
                        afpvec4 vab = afpvec4(unpackBFloat2x16(v.r), unpackBFloat2x16(v.g));
#else
                        afpvec4 vab = afpvec4(unpackHalf2x16(v.r), unpackHalf2x16(v.g));
#endif

                        const uvec4 oi4 = gm * p.outhstep + gn * 4 + uvec4(0, 1, 2, 3);

                        if (gn * 4 < psc(GN)) buffer_st1(top_blob_data, oi4.r, vab.r);
                        if (gn * 4 + 1 < psc(GN)) buffer_st1(top_blob_data, oi4.g, vab.g);
                        if (gn * 4 + 2 < psc(GN)) buffer_st1(top_blob_data, oi4.b, vab.b);
                        if (gn * 4 + 3 < psc(GN)) buffer_st1(top_blob_data, oi4.a, vab.a);
                    }
                }
            }
        }
    }
    else
    {
        //          +-M-+
        //          N   |
        //          +SG_UM
        //          |   |
        //       ^  +---+
        //       |  |   |
        //     SG_UN+- -+
        //       |  |   |
        //     ^ v  +---+
        //     |    |   |
        //     |    +- -+
        //     |    |   |
        //   WG_UM  +- -+
        //     |    |   |
        //     |    +- -+
        //     |    |   |
        //   ^ v    +---+
        //   |      |   |
        //   |      +- -+
        //   |      |   |
        //   |      +---+
        //   |      |   |
        //   |      +- -+
        //   |      |   |
        // WG_UN    +---+
        //   |      |   |
        //   |      +- -+
        //   |      |   |
        //   |      +---+
        //   |      |   |
        //   |      +- -+
        //   |      |   |
        //   v      +---+

        if (psc(out_elempack) == 4)
        {
            const uint Nd4_M_USGM_USGN = Nd4 * M * UNROLL_SG_M * UNROLL_SG_N;
            const uint Nd4_M_USGM_USGN_d_subgroupsize = (Nd4_M_USGM_USGN + subgroup_size - 1) / subgroup_size;
            [[unroll]] for (uint q = 0; q < Nd4_M_USGM_USGN_d_subgroupsize; q++)
            {
                const uint siq = si + q * subgroup_size;

                if (Nd4_M_USGM_USGN % subgroup_size == 0 || siq < Nd4_M_USGM_USGN)
                {
                    const uint zn = siq / (Nd4 * M * UNROLL_SG_M);
                    const uint zmij = siq % (Nd4 * M * UNROLL_SG_M);
                    const uint zm = zmij / (Nd4 * M);
                    const uint ij = zmij % (Nd4 * M);
                    const uint i = ij / Nd4;
                    const uint j = ij % Nd4;

                    const uint gm = (mi + zm) * M + i;
                    const uint gn = (ni + zn) * Nd4 + j;

                    if (gn * 4 < psc(GN) && gm < psc(GM))
                    {
                        uvec2 v = tmp_o[(((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * M + i) * Nd4p + j];

                        const uint gi = gn * p.outhstep + gm;

                        top_blob_data_4[gi] = v;
                    }
                }
            }
        }
        else
        {
            const uint Md4_N_USGM_USGN = Md4 * N * UNROLL_SG_M * UNROLL_SG_N;
            const uint Md4_N_USGM_USGN_d_subgroupsize = (Md4_N_USGM_USGN + subgroup_size - 1) / subgroup_size;
            [[unroll]] for (uint q = 0; q < Md4_N_USGM_USGN_d_subgroupsize; q++)
            {
                const uint siq = si + q * subgroup_size;

                if (Md4_N_USGM_USGN % subgroup_size == 0 || siq < Md4_N_USGM_USGN)
                {
                    const uint zn = siq / (Md4 * N * UNROLL_SG_M);
                    const uint zmij = siq % (Md4 * N * UNROLL_SG_M);
                    const uint zm = zmij / (Md4 * N);
                    const uint ij = zmij % (Md4 * N);
                    const uint i = ij / Md4;
                    const uint j = ij % Md4;

                    const uint gn = (ni + zn) * N + i;
                    const uint gm = (mi + zm) * Md4 + j;

                    if (gn < psc(GN))
                    {
                        uvec2 v = tmp_o[(((sgi * UNROLL_SG_N + zn) * UNROLL_SG_M + zm) * N + i) * Md4p + j];

#if NCNN_bf16_storage || NCNN_bf16_packed
                        afpvec4 vab = afpvec4(unpackBFloat2x16(v.r), unpackBFloat2x16(v.g));
#else
                        afpvec4 vab = afpvec4(unpackHalf2x16(v.r), unpackHalf2x16(v.g));
#endif

                        const uvec4 oi4 = gn * p.outhstep + (gm * 4 + uvec4(0, 1, 2, 3));

                        if (gm * 4 < psc(GM)) buffer_st1(top_blob_data, oi4.r, vab.r);
                        if (gm * 4 + 1 < psc(GM)) buffer_st1(top_blob_data, oi4.g, vab.g);
                        if (gm * 4 + 2 < psc(GM)) buffer_st1(top_blob_data, oi4.b, vab.b);
                        if (gm * 4 + 3 < psc(GM)) buffer_st1(top_blob_data, oi4.a, vab.a);
                    }
                }
            }
        }
    }
}
