// Copyright 2025 Futz12 <pchar.cn>
// SPDX-License-Identifier: BSD-3-Clause

#version 450

layout(constant_id = 0) const int affine = 0;
layout(constant_id = 1) const int affine_size = 0;

layout(binding = 0) buffer bottom_top_blob { sfpvec4 bottom_top_blob_data[]; };
layout(binding = 1) readonly buffer coeffs_blob { vec4 coeffs_blob_data[]; };
layout(binding = 2) readonly buffer gamma_blob { sfp gamma_data[]; };
layout(binding = 3) readonly buffer beta_blob { sfp beta_data[]; };

layout(push_constant) uniform parameter
{
    int w;
    int h;
    int c;
    int cstep;
} p;

void main()
{
    int gx = int(gl_GlobalInvocationID.x);
    int gy = int(gl_GlobalInvocationID.y);
    int gz = int(gl_GlobalInvocationID.z);

    if (gx >= p.w || gy >= p.h || gz >= p.c)
        return;

    const int gi = gz * p.cstep + gy * p.w + gx;
    const int q = gy * p.w + gx;
    const int group_id = gz * (p.w * p.h / affine_size) + q / affine_size;
    const int inner_id = q % affine_size;

    vec4 a = coeffs_blob_data[group_id * 2];
    vec4 b = coeffs_blob_data[group_id * 2 + 1];

    vec4 v = vec4(buffer_ld4(bottom_top_blob_data, gi));

    v = v * a + b;

    if (affine == 1)
    {
        float gamma = float(buffer_ld1(gamma_data, inner_id));
        float beta = float(buffer_ld1(beta_data, inner_id));
        v = v * vec4(gamma) + vec4(beta);
    }

    buffer_st4(bottom_top_blob_data, gi, afpvec4(v));
}
