// Copyright 2026 Tencent
// SPDX-License-Identifier: BSD-3-Clause

#version 450

layout(binding = 0) readonly buffer current_blob { sfp current_blob_data[]; };
layout(binding = 1) writeonly buffer cache_blob { sfp cache_blob_data[]; };

layout(push_constant) uniform parameter
{
    int current_seqlen;
    int head_dim;
    int cache_cstep;
    int old_seqlen;
} p;

void main()
{
    const int x = int(gl_GlobalInvocationID.x);
    const int y = int(gl_GlobalInvocationID.y);
    const int z = int(gl_GlobalInvocationID.z);

    if (x >= p.head_dim || y >= p.current_seqlen)
        return;

    const int src_index = (z * p.head_dim + x) * p.current_seqlen + y;
    const int dst_index = z * p.cache_cstep + (p.old_seqlen + y) * p.head_dim + x;
    buffer_cp1(cache_blob_data, dst_index, current_blob_data, src_index);
}
