// Copyright 2026 Futz12 <pchar.cn>
// SPDX-License-Identifier: BSD-3-Clause

#version 450

layout(constant_id = 0) const uint n = 0;
layout(constant_id = 1) const float threshold = 3.402823466e+38;
layout(constant_id = 2) const int has_threshold = 0;

layout(binding = 0) buffer bottom_top_blob { sfpvec4 bottom_top_blob_data[]; };

layout(push_constant) uniform parameter
{
    uint n;
} p;

void main()
{
    const uint gi = gl_GlobalInvocationID.x;

    if (gi >= psc(n))
        return;

    afpvec4 v = buffer_ld4(bottom_top_blob_data, gi);

    if (has_threshold == 0)
    {
        v = log(exp(v) + afpvec4(1.f));
    }
    else
    {
        vec4 x = vec4(v);
        vec4 y = log(exp(x) + vec4(1.f));
        v = afpvec4(mix(y, x, greaterThan(x, vec4(threshold))));
    }

    buffer_st4(bottom_top_blob_data, gi, v);
}
