name: libclc Tests

on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'clang/**'
      - 'llvm/**'
      - 'libclc/**'
      - '.github/workflows/libclc-tests.yml'
  pull_request:
    paths:
      - 'clang/**'
      - 'llvm/**'
      - 'libclc/**'
      - '.github/workflows/libclc-tests.yml'

jobs:
  build_libclc:
    name: libclc test 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # Disable build on windows, because I can't figure out where llvm-config is.
          #- windows-latest
          - macOS-latest
    steps:
    - name: Setup Windows
      if: startsWith(matrix.os, 'windows')
      uses: llvm/actions/setup-windows@master
      with:
        arch: amd64
    - name: Install Ninja
      uses: llvm/actions/install-ninja@master
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build clang
      uses: llvm/actions/build-test-llvm-project@master
      with:
        cmake_args: -G Ninja  -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE=Release
        build_target: ""
    - name: Build and test libclc
      run: |
        mkdir libclc-build
        cd libclc-build
        cmake -G Ninja ../libclc -DLLVM_CONFIG=../build/bin/llvm-config
        ninja
        ninja test
