name: Linux >64 CPU Support Test

on:
  push:
    branches: [ feature/support-64plus-cpu ]
  pull_request:
    branches: [ master ]

jobs:
  linux-build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Build NCNN
      run: |
        mkdir build
        cd build
        cmake -DNCNN_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)
        
    - name: Test CPU functionality
      run: |
        cd build
        ./tests/test_cpu
        
    - name: Run comprehensive tests
      run: |
        cd build
        ctest --output-on-failure --parallel $(nproc)
