name: linux-x64-cpu-gcc-sde
on:
  push:
    branches: [master]
    paths:
    - '.github/workflows/linux-x64-cpu-gcc-sde.yml'
    - 'CMakeLists.txt'
    - 'cmake/**'
    - 'src/*'
    - 'src/layer/*'
    - 'src/layer/x86/**'
    - 'tests/**'
    - 'tools/**'
    - '!tools/pnnx/**'
    - 'examples/**'
  pull_request:
    branches: [master]
    paths:
    - '.github/workflows/linux-x64-cpu-gcc-sde.yml'
    - 'CMakeLists.txt'
    - 'cmake/**'
    - 'src/*'
    - 'src/layer/*'
    - 'src/layer/x86/**'
    - 'tests/**'
    - 'tools/**'
    - '!tools/pnnx/**'
    - 'examples/**'
concurrency:
  group: linux-x64-cpu-gcc-sde-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  linux-gcc-sde:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update
    - name: gcc12
      run: sudo apt-get install gcc-12 g++-12
    - name: Setup SDE binaries
      uses: petarpetrovt/setup-sde@v2
    - name: build-avx512-spr
      env:
        CC: gcc-12
        CXX: g++-12
      run: |
        mkdir build-avx512-spr && cd build-avx512-spr
        cmake -DNCNN_BUILD_TESTS=ON ..
        cmake --build . -j 2
    - name: test-avx512-spr
      run: |
        cd build-avx512-spr
        TESTS_EXECUTABLE_LOADER=$SDE_PATH/sde64 TESTS_EXECUTABLE_LOADER_ARGUMENTS="-spr;--" ctest --output-on-failure -j 2

  linux-gcc-sde-coverage:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update
    - name: gcc12
      run: sudo apt-get install gcc-12 g++-12
    - name: lcov
      run: sudo apt-get install lcov
    - name: Setup SDE binaries
      uses: petarpetrovt/setup-sde@v2
    - name: build-avx512-spr
      env:
        CC: gcc-12
        CXX: g++-12
      run: |
        mkdir build-avx512-spr && cd build-avx512-spr
        cmake cmake -DCMAKE_BUILD_TYPE=debug -DNCNN_COVERAGE=ON -DNCNN_RUNTIME_CPU=OFF -DNCNN_AVX2=ON -DNCNN_AVX512=ON -DNCNN_AVX512VNNI=ON -DNCNN_AVX512BF16=ON -DNCNN_AVX512FP16=ON -DNCNN_XOP=OFF -DNCNN_OPENMP=ON -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF -DNCNN_BUILD_TESTS=ON ..
        cmake --build . -j 2
    - name: test-avx512-spr
      run: |
        cd build-avx512-spr
        TESTS_EXECUTABLE_LOADER=$SDE_PATH/sde64 TESTS_EXECUTABLE_LOADER_ARGUMENTS="-spr;--" ctest --output-on-failure -j 2
    - name: lcov-collect
      run: |
        cd build-avx512-spr
        lcov -d ./src -c -o lcov.info
        lcov -r lcov.info '/usr/*' -o lcov.info
        lcov -r lcov.info '*/build-avx512-spr/*' -o lcov.info
        lcov --list lcov.info
    - name: codecov-avx512-spr
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: build-avx512-spr/lcov.info
